# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Relational schema replacing the Neo4j graph.

SQLAlchemy Core table metadata — no ORM. Alembic autogenerates migrations by
diffing against :data:`METADATA`, so this file is the single source of truth for
the schema and ``docs/refactor/drop-neo4j/SCHEMA.md`` is its prose companion.

Design rationale lives in ``docs/refactor/drop-neo4j/PLAN.md`` § "Schema
design". The decisions that shape everything downstream:

* **``CONTAINS`` is a parent FK column, not an edge table.** This is what
  collapses ``reset.py``'s ``apoc.periodic.iterate`` + ``apoc.path.subgraphNodes``
  cascade into ``ON DELETE CASCADE``.
* **Ids are ``text`` uuids**, defaulted by ``gen_random_uuid()::text``. Not
  ``uuid``: every DAL signature is ``id: str``, and a malformed id arriving from
  a URL should yield an empty result as it does today, not a ``22P02`` 500.
  Not integers: ids are consumed as opaque strings by the pgvector row key
  (``f"neo4j:{node_id}"``), the frontend's pipe-separated focus param, and
  ``model_interchange``'s ``imported_id OR id`` match.
* **The catalog tier is prefixed ``catalog_``** — one rule that sidesteps
  ``table`` and ``column`` being reserved words and ``schema`` colliding with
  ``information_schema``, instead of three separate exceptions.
"""

from __future__ import annotations

from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

from gsf.dal.pg.session import SCHEMA

#: Naming convention so autogenerated constraints get stable, readable names.
#: Without it Alembic emits server-assigned names that differ between databases
#: and make a downgrade unable to find what it is dropping.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

METADATA = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)

#: ``gen_random_uuid()`` is built into Postgres from 13; no pgcrypto needed.
#: Replaces Cypher's ``ON CREATE SET n.id = randomUUID()`` exactly.
#:
#: Parenthesised to match how Postgres *stores* the expression. Written as
#: ``gen_random_uuid()::text`` it produces identical DDL, but the catalog reads
#: back ``(gen_random_uuid())::text``, and ``alembic check`` — which compares
#: server defaults as text — then reports drift on all 14 id columns on a
#: database that is perfectly up to date. Matching the normalised form keeps
#: the drift check meaningful instead of turning off ``compare_server_default``.
_UUID_DEFAULT = text("(gen_random_uuid())::text")


def _id() -> Column:
    return Column("id", Text, primary_key=True, server_default=_UUID_DEFAULT)


def _imported_id() -> Column:
    """Id carried over from a model-interchange export.

    ``_resolve_entities_batch`` matches YAML ids against ``imported_id OR id``,
    so an id from a previous export can arrive as an *imported* id on a node
    whose own id is different. Non-unique: two databases can legitimately import
    the same source model.
    """
    return Column("imported_id", Text, nullable=True)


# ---------------------------------------------------------------------------
# Catalog tier — Database -> Schema -> Table -> Column
# ---------------------------------------------------------------------------

catalog_database = Table(
    "catalog_database",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    # UI-managed connection form. Stored here only when Vault is not configured;
    # with Vault the credentials live there and this stays null (the database
    # name is the lookup key -- there is no separate reference field).
    Column("connection", JSONB, nullable=True),
    Column("dialect", Text, nullable=True),
    _imported_id(),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("pulled", DateTime(timezone=True), nullable=True),
)

catalog_schema = Table(
    "catalog_schema",
    METADATA,
    _id(),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    _imported_id(),
    UniqueConstraint("database_id", "name", name="uq_catalog_schema_database_name"),
)

catalog_table = Table(
    "catalog_table",
    METADATA,
    _id(),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    # Primary key column names. A list on the node today, so a text[] here
    # rather than a join table -- nothing ever queries "which tables have this
    # pk column", and a join table would make every read a second query.
    Column("pk", ARRAY(Text), nullable=True),
    Column("table_type", Text, nullable=True),
    _imported_id(),
    UniqueConstraint("schema_id", "name", name="uq_catalog_table_schema_name"),
)

catalog_column = Table(
    "catalog_column",
    METADATA,
    _id(),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("data_type", Text, nullable=True),
    # JSON string on the node today, and read back as a string by callers.
    # Kept as text rather than promoted to jsonb so the port stays behaviour
    # preserving; promoting it is a deliberate follow-up, not a porting detail.
    Column("sample_values", Text, nullable=True),
    Column("is_unique", Boolean, nullable=True),
    # Text, not Boolean, because the graph stores the *strings* 'YES' and 'NO'
    # -- measured on the fixture: 99 YES, 110 NO -- and the DAL returns the
    # value raw. A boolean column here would hand callers True/False where they
    # have always received 'YES'/'NO', which is a read-contract change wearing
    # the costume of a type fix.
    #
    # It should become a boolean, but as a deliberate change with its consumers
    # updated, not as a side effect of the port. See the is_nullable finding in
    # PROGRESS.md: `model_interchange` already reads this with `bool(...)`, and
    # `bool('NO')` is True, so every column currently exports as nullable.
    Column("is_nullable", Text, nullable=True),
    # INTEGER in the graph (verified: 209 of 209 columns), despite the parser
    # handing the write path a string -- something coerces on the way in.
    Column("ordinal_position", Integer, nullable=True),
    _imported_id(),
    UniqueConstraint("table_id", "name", name="uq_catalog_column_table_name"),
)

# FOREIGN_KEY: Column -> Column.
column_foreign_key = Table(
    "column_foreign_key",
    METADATA,
    Column(
        "source_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# JOIN: Table -> Table, carrying the columns that join them.
table_join = Table(
    "table_join",
    METADATA,
    Column(
        "source_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("join_columns", JSONB, nullable=True),
)

# ---------------------------------------------------------------------------
# SQL statements and their table references
# ---------------------------------------------------------------------------

sql_query = Table(
    "sql_query",
    METADATA,
    _id(),
    Column("sql_full_query", Text, nullable=False),
    Column("query_count", Integer, nullable=False, server_default=text("0")),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("last_seen", DateTime(timezone=True), nullable=True),
    # model_interchange matches a Sql node by its *text*
    # (match_props={"sql_full_query": sql}). Statement text can exceed the btree
    # row limit, so the uniqueness is enforced on a hash rather than the column.
    Index(
        "uq_sql_query_text_md5",
        func.md5(text("sql_full_query")),
        unique=True,
    ),
)

# SQL: Sql -> Table. An edge, because one statement references many tables and
# one table is referenced by many statements.
sql_query_table = Table(
    "sql_query_table",
    METADATA,
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# ---------------------------------------------------------------------------
# Semantic tier
# ---------------------------------------------------------------------------

term = Table(
    "term",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("synonyms", ARRAY(Text), nullable=True),
    Column("name_certified", Boolean, nullable=False, server_default=text("false")),
    Column(
        "description_certified", Boolean, nullable=False, server_default=text("false")
    ),
    _imported_id(),
    UniqueConstraint("name", "source", name="uq_term_name_source"),
)

# REPRESENTS: Table -> Term.
table_term = Table(
    "table_term",
    METADATA,
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

column_attribute = Table(
    "column_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("datatype", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("source_column", Text, nullable=False),
    Column("term_name", Text, nullable=False),
    # Deliberately NOT a foreign key, and deliberately not nullable. The
    # importer legitimately writes '' when col_ctx is missing
    # (model_interchange.py:1260), and this is compared as a plain string in
    # `ca.table_id IN $table_ids`. An FK here would reject valid imports.
    Column("table_id", Text, nullable=False),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    # The 5-part merge key, exactly as merge_column_attribute matches on.
    UniqueConstraint(
        "name",
        "source_column",
        "term_name",
        "table_id",
        "source",
        name="uq_column_attribute_merge_key",
    ),
)

# PROPERTY_OF: ColumnAttribute -> Term.
column_attribute_term = Table(
    "column_attribute_term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

# HAS_ATTRIBUTE and SEMANTIC_FK both run Column -> ColumnAttribute, but they
# assert different things and get their own tables rather than one table with a
# `kind` discriminator:
#
#   HAS_ATTRIBUTE  this column *is* an instance of the attribute
#   SEMANTIC_FK    this column *references* the attribute, which describes a
#                  column on another table
#
# Their cardinality already differs -- `resolve_semantic_fks` treats a column as
# unlinked when it has no SEMANTIC_FK, so at most one is expected, whereas a
# column can carry several attributes -- and a discriminator in the primary key
# makes any constraint that applies to only one of them impossible to express.
column_has_attribute = Table(
    "column_has_attribute",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

column_semantic_fk = Table(
    "column_semantic_fk",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

sql_attribute = Table(
    "sql_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    Column("expression", Text, nullable=True),
    Column("source", Text, nullable=True),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    CheckConstraint(
        "source IS NULL OR source IN ('manual', 'sql', 'table', 'bridgeTable')",
        name="source_value",
    ),
)

# PROPERTY_OF: SqlAttribute -> Term.
sql_attribute_term = Table(
    "sql_attribute_term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

# HAS_SQL: SqlAttribute -> Sql.
sql_attribute_sql = Table(
    "sql_attribute_sql",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

custom_analysis = Table(
    "custom_analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    _imported_id(),
)

# HAS_SQL: CustomAnalysis -> Sql.
custom_analysis_sql = Table(
    "custom_analysis_sql",
    METADATA,
    Column(
        "analysis_id",
        Text,
        ForeignKey(custom_analysis.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# Never attached to a Database -- which is why the scoped semantic reset does
# not reach it today, a behaviour DECISION-002/B2 preserves rather than fixes.
pql_analysis = Table(
    "pql_analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("pql", Text, nullable=True),
    _imported_id(),
)

# Declared in gsf/semantic/constants.py and referenced by reset.py's
# _SEMANTIC_LABELS, but never written by GSF today. Created so the reset
# cascade has something to point at and so a future writer needs no migration.
text_attribute = Table(
    "text_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

analysis = Table(
    "analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

# ---------------------------------------------------------------------------
# Zones
# ---------------------------------------------------------------------------

zone = Table(
    "zone",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    Column("color", Text, nullable=True),
    # Replaces the Zone/disableZone *label swap*. A boolean says the same thing
    # without the relabelling, which has no relational equivalent and which the
    # Cypher had to spell as `:Zone|disableZone` at every read site.
    Column("enabled", Boolean, nullable=False, server_default=text("true")),
)

# ZONE_OF is polymorphic: a zone can target a Database, a Schema or a Table.
# Three nullable FKs with a CHECK beats a (kind, id) pair because it keeps real
# referential integrity and lets a deleted table remove its zone membership by
# cascade -- a (kind, id) pair cannot have an FK at all, and would leave
# dangling grants behind, which is an access-control bug rather than untidiness.
zone_target = Table(
    "zone_target",
    METADATA,
    _id(),
    Column("zone_id", Text, ForeignKey(zone.c.id, ondelete="CASCADE"), nullable=False),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    CheckConstraint(
        "num_nonnulls(database_id, schema_id, table_id) = 1",
        name="exactly_one_target",
    ),
)

# ---------------------------------------------------------------------------
# Indexes for the read paths
# ---------------------------------------------------------------------------

Index("ix_catalog_schema_database_id", catalog_schema.c.database_id)
Index("ix_catalog_table_schema_id", catalog_table.c.schema_id)
Index("ix_catalog_table_name", catalog_table.c.name)
Index("ix_catalog_column_table_id", catalog_column.c.table_id)
Index("ix_catalog_column_name", catalog_column.c.name)

Index("ix_column_foreign_key_target", column_foreign_key.c.target_column_id)
Index("ix_table_join_target", table_join.c.target_table_id)
Index("ix_sql_query_table_table_id", sql_query_table.c.table_id)

Index("ix_term_name", term.c.name)
Index("ix_table_term_term_id", table_term.c.term_id)
Index("ix_column_attribute_term_name", column_attribute.c.term_name)
Index("ix_column_attribute_table_id", column_attribute.c.table_id)
Index("ix_column_attribute_term_term_id", column_attribute_term.c.term_id)
Index("ix_sql_attribute_term_term_id", sql_attribute_term.c.term_id)

# Both link tables are read in both directions -- from a column to its
# attributes, and from an attribute back to the columns that reference it
# (`fetch_attr_column_contexts` binds the attribute first). The composite
# primary key already indexes the column_id order; these cover the reverse.
Index("ix_column_has_attribute_attribute_id", column_has_attribute.c.attribute_id)
Index("ix_column_semantic_fk_attribute_id", column_semantic_fk.c.attribute_id)

Index("ix_zone_target_zone_id", zone_target.c.zone_id)
Index("ix_zone_target_database_id", zone_target.c.database_id)
Index("ix_zone_target_schema_id", zone_target.c.schema_id)
Index("ix_zone_target_table_id", zone_target.c.table_id)

# imported_id is matched alongside id during model import; non-unique.
for _table in (
    catalog_database,
    catalog_schema,
    catalog_table,
    catalog_column,
    term,
    column_attribute,
    sql_attribute,
    custom_analysis,
):
    Index(f"ix_{_table.name}_imported_id", _table.c.imported_id)

# ---------------------------------------------------------------------------
# join_path_edge view -- the traversal surface for find_join_path ONLY
# ---------------------------------------------------------------------------

#: Edge set for :func:`gsf.dal.attributes.find_join_path`, and **nothing else**.
#: Named for that function rather than generically, because its contents are
#: shaped by that one traversal's rules and are wrong for any other:
#:
#: * ``CONTAINS`` (Table <-> Column) and ``HAS_ATTRIBUTE``
#:   (Column <-> ColumnAttribute) appear in both directions.
#: * ``SEMANTIC_FK`` appears **outgoing only** (Column -> ColumnAttribute).
#:
#: Note carefully what that last line does *not* say. ``SEMANTIC_FK`` is
#: **stored** in one direction, but the codebase reads it in both:
#: ``fetch_attr_column_contexts`` binds a ColumnAttribute and finds the columns
#: referencing it, which is the reverse traversal. Anything needing that must
#: query :data:`column_semantic_fk` directly rather than this view.
#:
#: The restriction is specific to path-finding, and it is the whole reason the
#: Cypher needed ``apoc.path.expandConfig`` rather than a plain variable-length
#: pattern: allowed to traverse SEMANTIC_FK backwards, a path would hop from one
#: FK column up to a shared target attribute and back down a *different* FK
#: column, inventing a join between two columns that merely reference the same
#: thing -- two ``customer_id`` columns joined to each other. Here that is
#: simply a row the view does not emit.
JOIN_PATH_EDGE_VIEW_SQL = f"""
CREATE OR REPLACE VIEW {SCHEMA}.join_path_edge AS
    SELECT 'column'::text AS src_kind, c.id       AS src_id,
           'table'::text  AS dst_kind, c.table_id AS dst_id
      FROM {SCHEMA}.catalog_column c
    UNION ALL
    SELECT 'table', c.table_id, 'column', c.id
      FROM {SCHEMA}.catalog_column c
    UNION ALL
    SELECT 'column', h.column_id, 'column_attribute', h.attribute_id
      FROM {SCHEMA}.column_has_attribute h
    UNION ALL
    SELECT 'column_attribute', h.attribute_id, 'column', h.column_id
      FROM {SCHEMA}.column_has_attribute h
    UNION ALL
    SELECT 'column', f.column_id, 'column_attribute', f.attribute_id
      FROM {SCHEMA}.column_semantic_fk f
"""

DROP_JOIN_PATH_EDGE_VIEW_SQL = f"DROP VIEW IF EXISTS {SCHEMA}.join_path_edge"

__all__ = [
    "METADATA",
    "SCHEMA",
    "JOIN_PATH_EDGE_VIEW_SQL",
    "DROP_JOIN_PATH_EDGE_VIEW_SQL",
    "analysis",
    "catalog_column",
    "catalog_database",
    "catalog_schema",
    "catalog_table",
    "column_attribute",
    "column_has_attribute",
    "column_semantic_fk",
    "column_attribute_term",
    "column_foreign_key",
    "custom_analysis",
    "custom_analysis_sql",
    "pql_analysis",
    "sql_attribute",
    "sql_attribute_sql",
    "sql_attribute_term",
    "sql_query",
    "sql_query_table",
    "table_join",
    "table_term",
    "term",
    "text_attribute",
    "zone",
    "zone_target",
]
