# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tag CRUD on Postgres, and the objects a tag labels.

Concentrated on the two parts of a tag that are not a plain row.

The first is the name rule: unique case-insensitively on the *trimmed* name,
enforced twice — by a check in ``create_tag`` and ``update_tag`` and by
``uq_tag_name_lower`` underneath them — so the tests cover both halves on both
paths. The index is the one that matters, because it is what holds when the
check loses a race, and an index is exactly the sort of thing an autogenerated
migration silently drops. A rename asks one thing more of the rule than a
create does: a tag has to be allowed to keep its own name, and to change only
its case, neither of which is a collision with anybody.

``list_tag_targets`` is paged, and the page and ``count_tag_targets`` are read
from one union so they cannot disagree: a total the page can never reach would
have a scrolling caller asking for a next page forever.

The second is ``list_tag_targets``, which unions five kinds of tagged object
into one list. Five branches is five chances to join through the wrong column
and still return something plausible, so the fixture tags one of each kind at
once and the tests read the whole list rather than one kind at a time. Each row
carries the ids of the object's ancestors as well as their names, and those get
their own section below: names are checked by eye on the page, whereas a wrong
id is a link that silently opens somebody else's object.

The write path is covered for what a bare INSERT would not give: that labelling
something twice is not an error, that a missing tag or object is reported rather
than raised, and that both paths answer with the object's tags afterwards, which
is what a page redraws from.

The third is where a label *came from*, since a tag's page now names it. Two
sources write the same row — a person through ``attach_tag`` and a rule through
``attach_tags_by_rule`` — and the tests pin the rule that settles them: the
first source keeps the label, in both orders, because the second insert is
absorbed rather than applied. Deleting a rule gets its own set: it takes back
what it labelled, leaves alone what a person did, and — asked to keep the
labels — hands them to whoever wrote the rule instead, read from the rule rather
than from whoever is deleting it. They are that person's own labels from then
on, which is why the next identical rule does not adopt them either.

Needs a migrated database and skips without one.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timedelta, timezone

import pytest

pytest.importorskip("sqlalchemy")

from sqlalchemy import Select, select  # noqa: E402
from sqlalchemy.exc import IntegrityError  # noqa: E402

from auto_ontology.dal import schema as s  # noqa: E402
from auto_ontology.dal.pii import (  # noqa: E402
    is_column_safe_for_data_movement,
    purge_expired_sample_values,
)
from auto_ontology.dal.rules import delete_rule, update_rule  # noqa: E402
from auto_ontology.dal.session import store  # noqa: E402
from auto_ontology.dal.tags import (  # noqa: E402
    TARGET_COLUMN,
    TARGET_COLUMN_ATTRIBUTE,
    TARGET_SQL_ATTRIBUTE,
    TARGET_TABLE,
    TARGET_TERM,
    attach_tag,
    attach_tags_by_rule,
    count_tag_targets,
    count_tags,
    create_tag,
    delete_tag,
    detach_tag,
    existing_tag_ids,
    fetch_tags_map,
    get_tag,
    get_tag_by_name,
    get_or_create_tag,
    list_tag_targets,
    list_tags,
    apply_labels_now_matched,
    remove_labels_no_longer_matched,
    update_tag,
)


@pytest.fixture(scope="module", autouse=True)
def require_schema():
    if not os.environ.get("POSTGRES_USER"):
        pytest.skip("POSTGRES_* not set")
    try:
        store().query_read("SELECT 1 FROM tag_target LIMIT 1")
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"auto_ontology schema unavailable (alembic upgrade head): {exc}")


@pytest.fixture
def prefix():
    """A name prefix unique to this test, and its cleanup."""
    value = f"t-{uuid.uuid4().hex[:8]}"
    yield value
    store().query_write(s.tag.delete().where(s.tag.c.name.like(f"%{value}%")))


def test_create_returns_the_stored_tag(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")

    assert tag["name"] == f"{prefix}-pii"
    assert tag["id"]


def test_get_tag_by_name_ignores_case_and_whitespace(prefix) -> None:
    tag = create_tag(name=f"{prefix}-PII")

    found = get_tag_by_name(f"  {prefix}-pii  ")

    assert found is not None
    assert found["id"] == tag["id"]


def test_get_or_create_tag_reuses_existing_case_insensitive_name(prefix) -> None:
    tag = create_tag(name=f"{prefix}-PII")

    ensured = get_or_create_tag(name=f"{prefix}-pii")

    assert ensured["id"] == tag["id"]


def test_the_same_name_twice_is_rejected(prefix) -> None:
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"{prefix}-pii")


def test_the_name_rule_ignores_case(prefix) -> None:
    """A plain UNIQUE column would admit these two side by side."""
    create_tag(name=f"{prefix}-PII")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"{prefix}-pii")


def test_the_name_rule_ignores_surrounding_whitespace(prefix) -> None:
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"  {prefix}-pii  ")


def test_the_index_rejects_a_duplicate_the_check_never_saw(prefix) -> None:
    """The half that holds under a race: insert straight past ``create_tag``.

    Two concurrent creates can both pass the duplicate check before either
    inserts. This is that window, forced — and what makes it safe is the index,
    not the check.
    """
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(IntegrityError):
        store().query_write(s.tag.insert().values(name=f"{prefix}-PII  "))


def test_different_names_coexist(prefix) -> None:
    create_tag(name=f"{prefix}-pii")
    create_tag(name=f"{prefix}-gdpr")

    names = [row["name"] for row in list_tags() if prefix in row["name"]]
    assert names == [f"{prefix}-gdpr", f"{prefix}-pii"]


def test_the_listing_is_ordered_case_insensitively(prefix) -> None:
    """``ORDER BY name`` would put every capital ahead of every lowercase."""
    for name in (f"{prefix}-beta", f"{prefix}-Alpha", f"{prefix}-gamma"):
        create_tag(name=name)

    names = [row["name"] for row in list_tags() if prefix in row["name"]]
    assert names == [f"{prefix}-Alpha", f"{prefix}-beta", f"{prefix}-gamma"]


def test_a_page_of_tags_is_a_window_on_one_order(prefix) -> None:
    """Two pages of one list: neither repeats a tag nor skips one."""
    for name in (f"{prefix}-c", f"{prefix}-a", f"{prefix}-b"):
        create_tag(name=name)

    first = list_tags(search=prefix, skip=0, limit=2)
    second = list_tags(search=prefix, skip=2, limit=2)

    assert [row["name"] for row in first] == [f"{prefix}-a", f"{prefix}-b"]
    assert [row["name"] for row in second] == [f"{prefix}-c"]


def test_an_unpaged_read_returns_every_match(prefix) -> None:
    """What the tag picker asks for: the whole vocabulary, to filter locally."""
    for name in (f"{prefix}-a", f"{prefix}-b", f"{prefix}-c"):
        create_tag(name=name)

    assert len(list_tags(search=prefix)) == 3


def test_the_tag_total_counts_the_whole_match_not_the_page(prefix) -> None:
    for name in (f"{prefix}-a", f"{prefix}-b", f"{prefix}-c"):
        create_tag(name=name)

    assert len(list_tags(search=prefix, limit=2)) == 2
    assert count_tags(search=prefix) == 3


def test_a_search_matches_the_name_ignoring_case(prefix) -> None:
    create_tag(name=f"{prefix}-customers")
    create_tag(name=f"{prefix}-orders")

    found = list_tags(search=f"{prefix}-CUSTOM")

    assert [row["name"] for row in found] == [f"{prefix}-customers"]
    assert count_tags(search=f"{prefix}-CUSTOM") == 1


def test_a_blank_search_filters_nothing(prefix) -> None:
    """A cleared search box sends an empty string, not a missing parameter."""
    create_tag(name=f"{prefix}-pii")

    assert count_tags(search="   ") == count_tags()


def test_create_stamps_both_timestamps(prefix) -> None:
    """Both come from the database, and a fresh tag has not been modified."""
    tag = create_tag(name=f"{prefix}-pii")

    assert tag["created"].tzinfo is not None
    assert tag["modified"] == tag["created"]


def test_the_timestamps_survive_the_listing(prefix) -> None:
    """The list and create paths return the same shape -- ``_COLUMNS``."""
    created = create_tag(name=f"{prefix}-pii")

    listed = next(row for row in list_tags() if row["id"] == created["id"])
    assert listed == created


def test_an_update_advances_modified_and_leaves_created(prefix) -> None:
    """``onupdate`` is SQLAlchemy-side, so it only fires for DAL-issued writes.

    Pinned against a bare UPDATE rather than through ``update_tag``, because
    the column's contract is that *any* write the DAL issues gets the timestamp
    without naming it — which is what the next field added here will rely on.
    """
    tag = create_tag(name=f"{prefix}-pii")

    store().query_write(
        s.tag.update().where(s.tag.c.id == tag["id"]).values(name=f"{prefix}-gdpr")
    )

    updated = next(row for row in list_tags() if row["id"] == tag["id"])
    assert updated["created"] == tag["created"]
    assert updated["modified"] > tag["modified"]


def test_a_rename_returns_the_stored_tag(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-gdpr")

    assert renamed is not None
    assert renamed["id"] == tag["id"]
    assert renamed["name"] == f"{prefix}-gdpr"
    assert get_tag(tag["id"]) == renamed


def test_a_rename_advances_modified_and_leaves_created(prefix) -> None:
    """What the settings page reads to tell an edited tag from an untouched one.

    ``update_tag`` never names ``modified``, so this is also what pins the
    ``onupdate`` to the path a caller actually takes.
    """
    tag = create_tag(name=f"{prefix}-pii")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-gdpr")

    assert renamed is not None
    assert renamed["created"] == tag["created"]
    assert renamed["modified"] > tag["modified"]


def test_renaming_a_tag_that_is_not_there_reports_it(prefix) -> None:
    """What the router turns into a 404 rather than a silent success."""
    assert update_tag(tag_id=f"{prefix}-no-such-id", name=f"{prefix}-pii") is None


def test_create_records_its_author_and_no_editor(prefix) -> None:
    """A tag that has only been created has not been edited by anybody."""
    tag = create_tag(name=f"{prefix}-pii", created_by="user-1")

    assert tag["created_by"] == "user-1"
    assert tag["modified_by"] is None


def test_create_without_an_identity_records_nobody(prefix) -> None:
    """A direct call that skipped the gateway still creates the tag."""
    tag = create_tag(name=f"{prefix}-pii")

    assert tag["created_by"] is None


def test_a_rename_records_its_editor_and_keeps_the_author(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii", created_by="user-1")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-gdpr", modified_by="user-2")

    assert renamed is not None
    assert renamed["created_by"] == "user-1"
    assert renamed["modified_by"] == "user-2"


def test_a_rename_naming_nobody_clears_the_previous_editor(prefix) -> None:
    """Otherwise this edit reads as the work of whoever made the last one."""
    tag = create_tag(name=f"{prefix}-pii", created_by="user-1")
    update_tag(tag_id=tag["id"], name=f"{prefix}-gdpr", modified_by="user-2")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-ccpa")

    assert renamed is not None
    assert renamed["modified_by"] is None


def test_a_rename_onto_another_tags_name_is_rejected(prefix) -> None:
    create_tag(name=f"{prefix}-pii")
    other = create_tag(name=f"{prefix}-gdpr")

    with pytest.raises(ValueError):
        update_tag(tag_id=other["id"], name=f"{prefix}-pii")

    assert get_tag(other["id"])["name"] == f"{prefix}-gdpr"


def test_the_rename_name_rule_ignores_case_and_whitespace(prefix) -> None:
    """The same folding ``create_tag`` uses -- one rule, not two."""
    create_tag(name=f"{prefix}-pii")
    other = create_tag(name=f"{prefix}-gdpr")

    with pytest.raises(ValueError):
        update_tag(tag_id=other["id"], name=f"  {prefix}-PII  ")


def test_a_tag_may_be_renamed_to_its_own_name(prefix) -> None:
    """A tag collides with its own row, and that is not a duplicate.

    Without ``exclude_id`` the check would reject every rename that leaves the
    name alone, which is what a client sending the whole tag back would do.
    """
    tag = create_tag(name=f"{prefix}-pii")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-pii")

    assert renamed is not None
    assert renamed["name"] == f"{prefix}-pii"


def test_a_tag_may_be_recased(prefix) -> None:
    """The ordinary way to fix a tag created shouting.

    Folded, the name is unchanged, so this only works because the tag's own row
    is left out of the check *and* out of what the unique index compares
    against.
    """
    tag = create_tag(name=f"{prefix}-PII")

    renamed = update_tag(tag_id=tag["id"], name=f"{prefix}-pii")

    assert renamed is not None
    assert renamed["name"] == f"{prefix}-pii"


def test_the_index_rejects_a_rename_the_check_never_saw(prefix) -> None:
    """The half that holds when two renames race, as ``create_tag`` has too.

    Bypassing the check the way a lost race does: the duplicate reaches the
    UPDATE, and ``uq_tag_name_lower`` is what turns it into the same
    ``ValueError`` the check raises.
    """
    create_tag(name=f"{prefix}-pii")
    other = create_tag(name=f"{prefix}-gdpr")

    with pytest.raises(IntegrityError):
        store().query_write(
            s.tag.update().where(s.tag.c.id == other["id"]).values(name=f"{prefix}-PII")
        )


def test_renaming_frees_the_old_name(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")
    update_tag(tag_id=tag["id"], name=f"{prefix}-gdpr")

    assert create_tag(name=f"{prefix}-pii")["id"] != tag["id"]


def test_delete_removes_the_tag(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")

    assert delete_tag(tag["id"]) is True
    assert [row for row in list_tags() if row["id"] == tag["id"]] == []


def test_deleting_a_tag_that_is_not_there_reports_it(prefix) -> None:
    """What the router turns into a 404 instead of a silent success."""
    assert delete_tag(f"{prefix}-no-such-id") is False


def test_deleting_a_tag_frees_its_name(prefix) -> None:
    """The unique index covers live rows only, so the name comes back."""
    tag = create_tag(name=f"{prefix}-pii")
    delete_tag(tag["id"])

    assert create_tag(name=f"{prefix}-pii")["id"] != tag["id"]


def test_get_tag_returns_what_the_listing_returned(prefix) -> None:
    """One tag, not two projections of it -- ``_COLUMNS`` on both paths."""
    created = create_tag(name=f"{prefix}-pii")

    assert get_tag(created["id"]) == created


def test_get_tag_for_an_unknown_id_reports_it(prefix) -> None:
    """What the router turns into a 404 rather than an empty tag page."""
    assert get_tag(f"{prefix}-no-such-id") is None


def test_existing_ids_keeps_the_ones_that_are_tags_and_drops_the_rest(prefix) -> None:
    """What a rule's tags are checked against before it is saved."""
    tag = create_tag(name=f"{prefix}-pii")

    assert existing_tag_ids([tag["id"], f"{prefix}-no-such-id"]) == {tag["id"]}


def test_existing_ids_of_nothing_asks_the_database_nothing() -> None:
    """``IN ()`` is not a query, and the empty answer needs no read.

    No ``prefix``: this one writes nothing, so it needs neither a name to write
    under nor the cleanup that fixture exists for.
    """
    assert existing_tag_ids([]) == set()


# --------------------------------------------------------------------------
# list_tag_targets
# --------------------------------------------------------------------------


def _add(table, **values) -> str:
    return store().query_write(table.insert().values(**values).returning(table.c.id))[
        0
    ]["id"]


class Tagged:
    """A tag and one of each kind of object it could label.

    Every object hangs off one catalog path, ``<prefix>.shop.orders.total``, so
    a branch that joins through the wrong column shows up as a visibly wrong
    ``path`` rather than as a row that quietly went missing.

    Both attributes are linked to the Term as well, since that is the shape the
    write paths produce — ``merge_column_attribute`` refuses an attribute whose
    Term it cannot find, and ``set_term`` keeps a SqlAttribute on exactly one.
    """

    def __init__(self, prefix: str) -> None:
        self.prefix = prefix
        self.tag = create_tag(name=f"{prefix}-pii")["id"]

        self.database = _add(s.catalog_database, name=prefix)
        self.schema = _add(s.catalog_schema, database_id=self.database, name="shop")
        self.table = _add(s.catalog_table, schema_id=self.schema, name="orders")
        self.column = _add(s.catalog_column, table_id=self.table, name="total")
        self.term = _add(s.term, name=f"{prefix}-Order")
        self.column_attribute = _add(
            s.column_attribute,
            name=f"{prefix}-order-total",
            source_column="total",
            term_name=f"{prefix}-Order",
            table_id="",
        )
        self.sql_attribute = _add(s.sql_attribute, name=f"{prefix}-revenue")
        self.link(
            s.column_attribute__term,
            attribute_id=self.column_attribute,
            term_id=self.term,
        )
        self.link(
            s.sql_attribute__term,
            attribute_id=self.sql_attribute,
            term_id=self.term,
        )

    @staticmethod
    def link(table, **values) -> None:
        store().query_write(table.insert().values(**values))

    def rule(self, name: str, *, created_by: str = "user-1") -> str:
        """A stored rule, for the labels a rule applies to carry an id.

        Inserted rather than created through ``auto_ontology.dal.rules``: what a rule
        *searches* does not matter here — the search is replayed a layer up, in
        ``auto_ontology.server.rules.service`` — and only its id reaches this table.

        *created_by* is worth naming for the delete that keeps the labels: it
        hands them to the rule's author, so a test needs to be able to make one
        somebody in particular wrote.
        """
        return _add(
            s.rule,
            name=f"{self.prefix}-{name}",
            search_term=self.prefix,
            created_by=created_by,
        )

    def label(self, tag_id: str | None = None, **target) -> None:
        store().query_write(
            s.tag_target.insert().values(tag_id=tag_id or self.tag, **target)
        )

    def label_one_of_each(self) -> None:
        self.label(term_id=self.term)
        self.label(table_id=self.table)
        self.label(column_id=self.column)
        self.label(column_attribute_id=self.column_attribute)
        self.label(sql_attribute_id=self.sql_attribute)

    def items(self) -> dict[str, dict]:
        return {row["type"]: row for row in list_tag_targets(self.tag)}


@pytest.fixture
def tagged(prefix):
    world = Tagged(prefix)
    yield world

    # The tag itself, and so its labels, go with the `prefix` fixture.
    store().query_write(
        s.catalog_database.delete().where(s.catalog_database.c.id == world.database)
    )
    for table in (s.column_attribute, s.sql_attribute, s.term, s.rule):
        store().query_write(table.delete().where(table.c.name.like(f"{prefix}%")))


def test_a_tag_labelling_nothing_has_no_items(tagged) -> None:
    """The ordinary case: every tag today, and the page's empty state."""
    assert list_tag_targets(tagged.tag) == []


def test_an_unknown_tag_has_no_items(prefix) -> None:
    """Only ``get_tag`` distinguishes this from a tag labelling nothing."""
    assert list_tag_targets(f"{prefix}-no-such-id") == []


def test_a_page_is_a_window_on_one_order(tagged) -> None:
    """Two windows of one order: no object repeated between them, none missed."""
    tagged.label_one_of_each()

    whole = [row["id"] for row in list_tag_targets(tagged.tag)]
    first = [row["id"] for row in list_tag_targets(tagged.tag, limit=2)]
    rest = [row["id"] for row in list_tag_targets(tagged.tag, skip=2, limit=2)]

    assert len(whole) == 5
    assert first == whole[:2]
    assert rest == whole[2:4]


def test_a_page_past_the_end_is_empty_rather_than_an_error(tagged) -> None:
    tagged.label_one_of_each()

    assert list_tag_targets(tagged.tag, skip=500, limit=10) == []


def test_the_total_counts_everything_the_tag_labels_not_the_page(tagged) -> None:
    """What tells a scrolling caller when to stop asking."""
    tagged.label_one_of_each()

    assert len(list_tag_targets(tagged.tag, limit=2)) == 2
    assert count_tag_targets(tagged.tag) == 5


def test_a_tag_labelling_nothing_counts_zero(tagged) -> None:
    assert count_tag_targets(tagged.tag) == 0


def test_an_unknown_tag_counts_zero(prefix) -> None:
    """As the list does: only ``get_tag`` tells this from a tag with no items."""
    assert count_tag_targets(f"{prefix}-no-such-id") == 0


def test_each_kind_of_object_appears_exactly_once(tagged) -> None:
    """Five branches, five rows -- no kind dropped and none duplicated."""
    tagged.label_one_of_each()

    types = sorted(row["type"] for row in list_tag_targets(tagged.tag))
    assert types == sorted(
        [
            TARGET_COLUMN,
            TARGET_COLUMN_ATTRIBUTE,
            TARGET_SQL_ATTRIBUTE,
            TARGET_TABLE,
            TARGET_TERM,
        ]
    )


def test_a_tagged_term_has_no_path(tagged) -> None:
    """A glossary entry sits under no catalog path, so there is none to show."""
    tagged.label_one_of_each()

    item = tagged.items()[TARGET_TERM]
    assert item["id"] == tagged.term
    assert item["name"] == f"{tagged.prefix}-Order"
    assert item["path"] is None


def test_a_tagged_table_is_qualified_by_its_database_and_schema(tagged) -> None:
    tagged.label_one_of_each()

    item = tagged.items()[TARGET_TABLE]
    assert item["id"] == tagged.table
    assert item["name"] == "orders"
    assert item["path"] == f"{tagged.prefix}.shop"


def test_a_tagged_column_is_qualified_down_to_its_table(tagged) -> None:
    """Three joins deep, which is where a wrong one would surface."""
    tagged.label_one_of_each()

    item = tagged.items()[TARGET_COLUMN]
    assert item["id"] == tagged.column
    assert item["name"] == "total"
    assert item["path"] == f"{tagged.prefix}.shop.orders"


def test_both_kinds_of_attribute_are_qualified_by_their_term(tagged) -> None:
    """The two are properties of a Term in the same sense, so they read alike.

    Asserted together rather than one test each, because "the same" is the
    property at issue: they used to differ, the SqlAttribute showing no
    location at all, and only a comparison can fail when that comes back.
    """
    tagged.label_one_of_each()

    items = tagged.items()
    assert items[TARGET_COLUMN_ATTRIBUTE]["id"] == tagged.column_attribute
    assert items[TARGET_SQL_ATTRIBUTE]["id"] == tagged.sql_attribute
    assert (
        items[TARGET_COLUMN_ATTRIBUTE]["path"]
        == items[TARGET_SQL_ATTRIBUTE]["path"]
        == f"{tagged.prefix}-Order"
    )


def test_the_path_of_an_attribute_is_its_linked_term_not_its_stored_name(
    tagged,
) -> None:
    """``column_attribute.term_name`` is a denormalised copy, and can be stale.

    Reading it would let ``path`` name one Term while ``term_id`` opens
    another -- a row that says where it lives and then goes somewhere else.
    """
    store().query_write(
        s.column_attribute.update()
        .where(s.column_attribute.c.id == tagged.column_attribute)
        .values(term_name=f"{tagged.prefix}-Stale")
    )
    tagged.label(column_attribute_id=tagged.column_attribute)

    item = tagged.items()[TARGET_COLUMN_ATTRIBUTE]
    assert item["path"] == f"{tagged.prefix}-Order"
    assert item["term_id"] == tagged.term


# --------------------------------------------------------------------------
# The ancestor ids, which are what a link to the object's own page is built
# from. `path` says the same thing in names, and the names are not unique, so
# nothing downstream could derive these -- a wrong one here is a row that opens
# somebody else's page.
# --------------------------------------------------------------------------


def _ancestors(item: dict) -> dict:
    return {
        field: item[field]
        for field in ("database_id", "schema_id", "table_id", "term_id")
    }


def test_a_tagged_term_has_no_ancestors(tagged) -> None:
    """Its page is addressed by its own id, so there is nothing else to carry."""
    tagged.label_one_of_each()

    assert _ancestors(tagged.items()[TARGET_TERM]) == {
        "database_id": None,
        "schema_id": None,
        "table_id": None,
        "term_id": None,
    }


def test_a_tagged_table_carries_the_ids_down_to_its_schema(tagged) -> None:
    tagged.label_one_of_each()

    assert _ancestors(tagged.items()[TARGET_TABLE]) == {
        "database_id": tagged.database,
        "schema_id": tagged.schema,
        "table_id": None,
        "term_id": None,
    }


def test_a_tagged_column_carries_its_whole_chain(tagged) -> None:
    """The deepest one, and the only kind that fills three of the four."""
    tagged.label_one_of_each()

    assert _ancestors(tagged.items()[TARGET_COLUMN]) == {
        "database_id": tagged.database,
        "schema_id": tagged.schema,
        "table_id": tagged.table,
        "term_id": None,
    }


def test_both_kinds_of_attribute_carry_only_their_term_id(tagged) -> None:
    """Together, for the reason the ``path`` pair above is."""
    tagged.label_one_of_each()

    only_the_term = {
        "database_id": None,
        "schema_id": None,
        "table_id": None,
        "term_id": tagged.term,
    }
    items = tagged.items()
    assert _ancestors(items[TARGET_COLUMN_ATTRIBUTE]) == only_the_term
    assert _ancestors(items[TARGET_SQL_ATTRIBUTE]) == only_the_term


@pytest.mark.parametrize(
    ("link_table", "attribute"),
    [
        (s.column_attribute__term, "column_attribute"),
        (s.sql_attribute__term, "sql_attribute"),
    ],
)
def test_an_attribute_cannot_be_a_property_of_two_terms(
    tagged, link_table, attribute
) -> None:
    """What lets ``_attribute_term`` join instead of deduplicate.

    Both link tables key on ``(attribute_id, term_id)``, which on its own would
    admit a second Term -- and then the join would list one tagged attribute
    once per Term, when one tag on one object is one row. The unique constraint
    on ``attribute_id`` is what refuses it, on both kinds alike.
    """
    second = _add(s.term, name=f"{tagged.prefix}-Purchase")

    with pytest.raises(IntegrityError, match="attribute_id"):
        tagged.link(link_table, attribute_id=getattr(tagged, attribute), term_id=second)


def test_the_items_are_ordered_case_insensitively(tagged) -> None:
    """``ORDER BY name`` would put every capital ahead of every lowercase.

    Across branches too, not within one: the union's own order is whichever
    branch ran first, so this is what stops the list reshuffling by kind.
    """
    for name in ("beta", "Alpha", "gamma"):
        tagged.label(column_id=_add(s.catalog_column, table_id=tagged.table, name=name))

    names = [row["name"] for row in list_tag_targets(tagged.tag)]
    assert names == ["Alpha", "beta", "gamma"]


def test_another_tags_objects_are_not_listed(tagged) -> None:
    other = create_tag(name=f"{tagged.prefix}-gdpr")["id"]
    tagged.label(tag_id=other, table_id=tagged.table)
    tagged.label(column_id=tagged.column)

    assert [row["type"] for row in list_tag_targets(tagged.tag)] == [TARGET_COLUMN]


def test_deleting_a_tagged_object_removes_its_label(tagged) -> None:
    """The reason the targets are real foreign keys and not a (kind, id) pair.

    Without the cascade the row survives its object and the page lists
    something that no longer exists.
    """
    tagged.label_one_of_each()

    store().query_write(
        s.catalog_column.delete().where(s.catalog_column.c.id == tagged.column)
    )

    assert TARGET_COLUMN not in tagged.items()
    assert TARGET_TABLE in tagged.items()


def test_deleting_the_tag_leaves_the_objects_it_labelled(tagged) -> None:
    """Deleting a tag unlabels; it does not delete anyone's data."""
    tagged.label_one_of_each()

    delete_tag(tagged.tag)

    assert store().query_read(
        s.catalog_column.select().where(s.catalog_column.c.id == tagged.column)
    )


def test_renaming_the_tag_leaves_its_labels_alone(tagged) -> None:
    """Membership is keyed by id, so a rename writes no ``tag_target`` row.

    The point being that the new name reaches every object already carrying the
    tag -- the chips a page draws come from ``fetch_tags_map``, which reads the
    name through the join rather than storing a copy of it.
    """
    tagged.label_one_of_each()

    update_tag(tag_id=tagged.tag, name=f"{tagged.prefix}-gdpr")

    assert set(tagged.items()) == {
        TARGET_TERM,
        TARGET_TABLE,
        TARGET_COLUMN,
        TARGET_COLUMN_ATTRIBUTE,
        TARGET_SQL_ATTRIBUTE,
    }
    chips = fetch_tags_map(TARGET_COLUMN, [tagged.column])[tagged.column]
    assert [chip["name"] for chip in chips] == [f"{tagged.prefix}-gdpr"]


def test_a_label_must_point_at_exactly_one_object(tagged) -> None:
    """``exactly_one_target``: two targets in one row, or none, is neither."""
    with pytest.raises(IntegrityError):
        tagged.label(table_id=tagged.table, column_id=tagged.column)

    with pytest.raises(IntegrityError):
        tagged.label()


def test_the_same_object_cannot_carry_a_tag_twice(tagged) -> None:
    """One of the unique constraints, which need NULLs to be distinct."""
    tagged.label(table_id=tagged.table)

    with pytest.raises(IntegrityError):
        tagged.label(table_id=tagged.table)


def test_one_tag_on_two_objects_of_the_same_kind_is_allowed(tagged) -> None:
    """The other half of that rule: the constraint is per object, not per kind.

    One constraint per nullable column is a shape that can easily enforce too
    much -- this is what says it does not.
    """
    tagged.label(table_id=tagged.table)
    tagged.label(
        table_id=_add(s.catalog_table, schema_id=tagged.schema, name="customers")
    )

    assert len(list_tag_targets(tagged.tag)) == 2


# --------------------------------------------------------------------------
# fetch_tags_map -- membership read from the object's side
# --------------------------------------------------------------------------


def test_the_tags_on_an_object_are_its_own(tagged) -> None:
    """The reverse read of ``list_tag_targets``, and the chip a page draws."""
    other = create_tag(name=f"{tagged.prefix}-gdpr")["id"]
    tagged.label(term_id=tagged.term)
    tagged.label(tag_id=other, term_id=tagged.term)
    tagged.label(table_id=tagged.table)

    tags = fetch_tags_map(TARGET_TERM, [tagged.term])[tagged.term]
    assert [tag["name"] for tag in tags] == [
        f"{tagged.prefix}-gdpr",
        f"{tagged.prefix}-pii",
    ]
    assert set(tags[0]) == {"id", "name"}


def test_an_untagged_object_is_absent_rather_than_empty(tagged) -> None:
    """What makes ``.get(id, [])`` the same call whichever way the read went."""
    assert fetch_tags_map(TARGET_TERM, [tagged.term]) == {}


def test_the_map_resolves_every_object_in_one_pass(tagged) -> None:
    """The reason it takes a list: one query for a page, not one per row."""
    second = _add(s.term, name=f"{tagged.prefix}-Customer")
    tagged.label(term_id=tagged.term)
    tagged.label(term_id=second)

    assert set(fetch_tags_map(TARGET_TERM, [tagged.term, second])) == {
        tagged.term,
        second,
    }


def test_the_map_reads_only_the_kind_it_was_asked_for(tagged) -> None:
    """Ids are unique across tables, but the column filtered on is not."""
    tagged.label_one_of_each()

    assert fetch_tags_map(TARGET_TERM, [tagged.table]) == {}


def test_an_unknown_kind_is_a_programming_error(tagged) -> None:
    """Not a missing object -- a caller naming something the API never had."""
    with pytest.raises(ValueError, match="Unknown tag target"):
        fetch_tags_map("database", [tagged.database])


# --------------------------------------------------------------------------
# attach_tag / detach_tag
# --------------------------------------------------------------------------


def test_attaching_labels_the_object_and_answers_with_its_tags(tagged) -> None:
    tags = attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    assert [tag["name"] for tag in tags] == [f"{tagged.prefix}-pii"]
    assert [row["id"] for row in list_tag_targets(tagged.tag)] == [tagged.term]


def test_attaching_works_for_every_kind(tagged) -> None:
    """One mapping from kind to column, exercised through all five of them."""
    for kind, item_id in (
        (TARGET_TERM, tagged.term),
        (TARGET_TABLE, tagged.table),
        (TARGET_COLUMN, tagged.column),
        (TARGET_COLUMN_ATTRIBUTE, tagged.column_attribute),
        (TARGET_SQL_ATTRIBUTE, tagged.sql_attribute),
    ):
        assert attach_tag(tag_id=tagged.tag, kind=kind, item_id=item_id) is not None

    assert len(list_tag_targets(tagged.tag)) == 5


def test_attaching_pii_to_column_deletes_persisted_samples(tagged) -> None:
    pii_tag = get_or_create_tag(name="PII")
    store().query_write(
        s.catalog_column.update()
        .where(s.catalog_column.c.id == tagged.column)
        .values(sample_values='["person@example.com"]')
    )

    attach_tag(tag_id=pii_tag["id"], kind=TARGET_COLUMN, item_id=tagged.column)

    row = store().query_read(
        select(s.catalog_column.c.sample_values).where(
            s.catalog_column.c.id == tagged.column
        )
    )[0]
    assert row["sample_values"] is None


def test_data_movement_policy_fails_closed_for_unprocessed_and_pii(tagged) -> None:
    reference = {
        "database_name": tagged.prefix,
        "schema_name": "shop",
        "table_name": "orders",
        "column_name": "total",
    }
    assert is_column_safe_for_data_movement(**reference) is False

    store().query_write(
        s.catalog_column.update()
        .where(s.catalog_column.c.id == tagged.column)
        .values(pii_processed=True)
    )
    assert is_column_safe_for_data_movement(**reference) is True

    pii_tag = get_or_create_tag(name="PII")
    attach_tag(tag_id=pii_tag["id"], kind=TARGET_COLUMN, item_id=tagged.column)
    assert is_column_safe_for_data_movement(**reference) is False


def test_expired_samples_are_deleted(tagged) -> None:
    store().query_write(
        s.catalog_column.update()
        .where(s.catalog_column.c.id == tagged.column)
        .values(
            sample_values='["old"]',
            sample_values_updated_at=datetime.now(timezone.utc) - timedelta(days=31),
        )
    )

    assert purge_expired_sample_values(retention_days=30) >= 1

    row = store().query_read(
        select(
            s.catalog_column.c.sample_values,
            s.catalog_column.c.sample_values_updated_at,
        ).where(s.catalog_column.c.id == tagged.column)
    )[0]
    assert row["sample_values"] is None
    assert row["sample_values_updated_at"] is None


def test_attaching_the_same_tag_twice_is_not_an_error(tagged) -> None:
    """Two clicks on one tag are one intention, and the unique row holds.

    Straight through the constraint that ``test_the_same_object_cannot_carry_a
    _tag_twice`` shows raising, so this pins the ``ON CONFLICT`` above it.
    """
    first = attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)
    again = attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    assert again == first
    assert len(list_tag_targets(tagged.tag)) == 1


def test_attaching_to_an_object_that_is_gone_is_reported(tagged) -> None:
    """The foreign key catches it; the router owes a 404, not a 500."""
    assert (
        attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=str(uuid.uuid4()))
        is None
    )


def test_attaching_a_tag_that_is_gone_is_reported(tagged) -> None:
    assert (
        attach_tag(tag_id=str(uuid.uuid4()), kind=TARGET_TERM, item_id=tagged.term)
        is None
    )


def test_an_attribute_of_no_term_cannot_be_tagged(tagged) -> None:
    """Both kinds, one rule.

    A SqlAttribute can reach a CustomAnalysis instead of a Term, and neither
    kind appears in any list that is not a Term's -- so a tag on one would be
    invisible from both ends: no page shows the object, and the tag's own page
    could not open it to take the label off.
    """
    orphans = (
        (
            TARGET_SQL_ATTRIBUTE,
            _add(s.sql_attribute, name=f"{tagged.prefix}-orphan-sql"),
        ),
        (
            TARGET_COLUMN_ATTRIBUTE,
            _add(
                s.column_attribute,
                name=f"{tagged.prefix}-orphan-col",
                source_column="total",
                term_name=f"{tagged.prefix}-Order",
                table_id="",
            ),
        ),
    )
    for kind, item_id in orphans:
        with pytest.raises(ValueError, match="not a property of any term"):
            attach_tag(tag_id=tagged.tag, kind=kind, item_id=item_id)

    assert list_tag_targets(tagged.tag) == []


def test_a_stored_term_name_is_not_a_term_link(tagged) -> None:
    """The orphan above carries a ``term_name``, and it is not enough.

    ``column_attribute.term_name`` is a denormalised string with no foreign
    key, so treating it as the link would admit exactly the untaggable
    attribute this rule exists to keep out.
    """
    attribute = _add(
        s.column_attribute,
        name=f"{tagged.prefix}-named-but-unlinked",
        source_column="total",
        term_name=f"{tagged.prefix}-Order",
        table_id="",
    )

    with pytest.raises(ValueError, match="not a property of any term"):
        attach_tag(tag_id=tagged.tag, kind=TARGET_COLUMN_ATTRIBUTE, item_id=attribute)


def test_an_attribute_that_is_gone_is_a_miss_rather_than_ineligible(tagged) -> None:
    """The two answers the router owes different codes: 404, not 409.

    An id with no row cannot be shown to be a property of anything, so the
    eligibility check must decline to judge it and leave the foreign key to
    report it.
    """
    assert (
        attach_tag(
            tag_id=tagged.tag,
            kind=TARGET_SQL_ATTRIBUTE,
            item_id=str(uuid.uuid4()),
        )
        is None
    )


def test_detaching_removes_only_that_label(tagged) -> None:
    other = create_tag(name=f"{tagged.prefix}-gdpr")["id"]
    attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)
    attach_tag(tag_id=other, kind=TARGET_TERM, item_id=tagged.term)

    remaining = detach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    assert [tag["id"] for tag in remaining] == [other]


def test_detaching_the_last_tag_leaves_an_empty_list_not_a_miss(tagged) -> None:
    """``[]`` says "none left"; ``None`` says "there was nothing to remove"."""
    attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    assert detach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term) == []


def test_detaching_a_label_that_is_not_there_is_reported(tagged) -> None:
    """A stale page removing a chip the object never carried."""
    assert detach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term) is None


def test_detaching_leaves_the_object_alone(tagged) -> None:
    """It unlabels; the cascade runs the other way."""
    attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)
    detach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    assert store().query_read(s.term.select().where(s.term.c.id == tagged.term))


# --------------------------------------------------------------------------
# Where a label came from
# --------------------------------------------------------------------------


def test_a_hand_applied_label_records_the_account(tagged) -> None:
    attach_tag(
        tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term, tagged_by="user-1"
    )

    item = tagged.items()[TARGET_TERM]
    assert item["tagged_by"] == "user-1"
    assert item["rule"] is None


def test_a_label_with_no_identity_names_nobody(tagged) -> None:
    """Neither column set, which the page reads as "Auto Generated"."""
    attach_tag(tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term)

    item = tagged.items()[TARGET_TERM]
    assert item["tagged_by"] is None
    assert item["rule"] is None


def test_a_rule_applied_label_names_the_rule(tagged) -> None:
    rule_id = tagged.rule("pii-everywhere")
    applied = attach_tags_by_rule(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets=[(TARGET_TERM, tagged.term), (TARGET_TABLE, tagged.table)],
    )

    assert applied == 2
    items = tagged.items()
    assert items[TARGET_TERM]["rule"] == {
        "id": rule_id,
        "name": f"{tagged.prefix}-pii-everywhere",
    }
    assert items[TARGET_TERM]["tagged_by"] is None
    assert items[TARGET_TABLE]["rule"]["id"] == rule_id


def test_renaming_a_rule_renames_it_on_everything_it_labelled(tagged) -> None:
    """The point of naming the rule by id rather than copying its name here."""
    rule_id = tagged.rule("pii")
    attach_tags_by_rule(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets=[(TARGET_TERM, tagged.term), (TARGET_TABLE, tagged.table)],
    )

    update_rule(rule_id=rule_id, name=f"{tagged.prefix}-sensitive")

    items = tagged.items()
    assert items[TARGET_TERM]["rule"]["name"] == f"{tagged.prefix}-sensitive"
    assert items[TARGET_TABLE]["rule"]["name"] == f"{tagged.prefix}-sensitive"


def test_a_rule_labels_every_object_with_every_tag_it_applies(tagged) -> None:
    """The pairs are the cross product, which is what "applies these" means."""
    second = create_tag(name=f"{tagged.prefix}-confidential")["id"]

    applied = attach_tags_by_rule(
        rule_id=tagged.rule("two-tags"),
        tag_ids=[tagged.tag, second],
        targets=[(TARGET_TERM, tagged.term), (TARGET_TABLE, tagged.table)],
    )

    assert applied == 4


def test_a_rule_re_applying_itself_costs_nothing(tagged) -> None:
    """The hook that re-runs a rule as the catalog grows can be a plain call."""
    rule_id = tagged.rule("again")
    targets = [(TARGET_TERM, tagged.term)]

    assert (
        attach_tags_by_rule(rule_id=rule_id, tag_ids=[tagged.tag], targets=targets) == 1
    )
    assert (
        attach_tags_by_rule(rule_id=rule_id, tag_ids=[tagged.tag], targets=targets) == 0
    )
    assert len(list_tag_targets(tagged.tag)) == 1


def test_a_rule_does_not_take_over_a_label_a_person_applied(tagged) -> None:
    """First source keeps the label, which is what the absorbed insert means."""
    attach_tag(
        tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term, tagged_by="user-1"
    )

    applied = attach_tags_by_rule(
        rule_id=tagged.rule("late"),
        tag_ids=[tagged.tag],
        targets=[(TARGET_TERM, tagged.term)],
    )

    item = tagged.items()[TARGET_TERM]
    assert applied == 0
    assert item["tagged_by"] == "user-1"
    assert item["rule"] is None


def test_a_rule_applied_label_names_no_account(tagged) -> None:
    """A rule is not an account, and ``rule_id`` is what says a rule did it."""
    attach_tags_by_rule(
        rule_id=tagged.rule("named"),
        tag_ids=[tagged.tag],
        targets=[(TARGET_TERM, tagged.term)],
    )

    assert tagged.items()[TARGET_TERM]["tagged_by"] is None


def test_a_person_does_not_take_over_a_label_a_rule_applied(tagged) -> None:
    rule_id = tagged.rule("first")
    attach_tags_by_rule(
        rule_id=rule_id, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )

    attach_tag(
        tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term, tagged_by="user-1"
    )

    item = tagged.items()[TARGET_TERM]
    assert item["rule"]["id"] == rule_id
    assert item["tagged_by"] is None


def test_nothing_to_do_is_not_a_query(tagged) -> None:
    """A rule matching nothing is a standing instruction, not a failure."""
    assert attach_tags_by_rule(rule_id=tagged.rule("x"), tag_ids=[], targets=[]) == 0
    assert (
        attach_tags_by_rule(rule_id=tagged.rule("y"), tag_ids=[tagged.tag], targets=[])
        == 0
    )


def test_deleting_a_rule_takes_back_what_it_labelled(tagged) -> None:
    """``ON DELETE CASCADE``: the label was the rule holding, not a fact."""
    rule_id = tagged.rule("temporary")
    attach_tags_by_rule(
        rule_id=rule_id, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )

    store().query_write(s.rule.delete().where(s.rule.c.id == rule_id))

    assert list_tag_targets(tagged.tag) == []


def test_deleting_a_rule_leaves_a_hand_applied_label(tagged) -> None:
    """The cascade follows ``rule_id``, and a hand-applied row does not have one."""
    attach_tag(
        tag_id=tagged.tag, kind=TARGET_TERM, item_id=tagged.term, tagged_by="user-1"
    )
    rule_id = tagged.rule("elsewhere")
    attach_tags_by_rule(
        rule_id=rule_id, tag_ids=[tagged.tag], targets=[(TARGET_TABLE, tagged.table)]
    )

    store().query_write(s.rule.delete().where(s.rule.c.id == rule_id))

    assert [row["id"] for row in list_tag_targets(tagged.tag)] == [tagged.term]


def test_a_rule_can_be_deleted_and_leave_its_labels_behind(tagged) -> None:
    """``keep_tags``: handed to the rule's author, so the cascade finds none."""
    rule_id = tagged.rule("suggestion")
    attach_tags_by_rule(
        rule_id=rule_id, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )

    assert delete_rule(rule_id, keep_tags=True) is True

    item = tagged.items()[TARGET_TERM]
    assert item["id"] == tagged.term
    # The rule is gone and the person who wrote it is named instead -- these
    # are that person's labels now, not nobody's.
    assert item["rule"] is None
    assert item["tagged_by"] == "user-1"


def test_the_labels_kept_go_to_the_author_of_that_rule(tagged) -> None:
    """Read from the rule, so a delete by an admin is not a claim of authorship."""
    rule_id = tagged.rule("somebody-elses", created_by="user-2")
    attach_tags_by_rule(
        rule_id=rule_id, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )

    delete_rule(rule_id, keep_tags=True)

    assert tagged.items()[TARGET_TERM]["tagged_by"] == "user-2"


def test_a_label_left_behind_is_not_adopted_by_the_next_rule(tagged) -> None:
    """It is a person's label now, and a rule claims no existing row."""
    first = tagged.rule("first")
    attach_tags_by_rule(
        rule_id=first, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )
    delete_rule(first, keep_tags=True)

    attach_tags_by_rule(
        rule_id=tagged.rule("second"),
        tag_ids=[tagged.tag],
        targets=[(TARGET_TERM, tagged.term)],
    )

    assert tagged.items()[TARGET_TERM]["rule"] is None


# --------------------------------------------------------------------------
# Re-applying a rule as the catalog changes
# --------------------------------------------------------------------------
#
# The ingest path, and the one place in this module that takes *statements*
# rather than ids: the match runs inside the write, so what a test hands over
# is a query and what it checks is which rows the database decided on.
#
# Plain selects here, built by hand rather than taken from
# ``auto_ontology.dal.search``. This module does not know how a search is spelled -- it
# knows how to apply one -- and a test that imported the search would be
# checking two modules at once and failing for either.
#
# ``_sync`` below is one rule's two halves back to back, which is what most of
# these tests are about: what a single rule does to its own labels. The order
# the halves run in across *rules* belongs to
# ``auto_ontology.server.rules.service.reapply_rules`` and is tested there --
# except for the one case that is a property of these statements rather than of
# the loop, which has its own section at the end.


def _sync(
    *, rule_id: str, tag_ids: list[str], targets: dict[str, Select]
) -> tuple[int, int]:
    """One rule's replay: take back what it no longer matches, apply the rest."""
    removed = remove_labels_no_longer_matched(rule_id=rule_id, targets=targets)
    applied = apply_labels_now_matched(
        rule_id=rule_id, tag_ids=tag_ids, targets=targets
    )
    return applied, removed


def _columns_named(like: str, table_id: str) -> Select:
    """A ``SELECT id`` standing in for whatever a rule's search matches.

    Scoped to the test's own table as well as the name. A real rule is scoped
    to nothing -- that is the point of it -- but the database this runs
    against holds a catalog of its own, and a match on ``total%`` alone
    reaches the seeded columns too and labels rows the test did not make.
    """
    return select(s.catalog_column.c.id).where(
        s.catalog_column.c.table_id == table_id,
        s.catalog_column.c.name.like(like),
    )


def _tagged_dates(tag_id: str) -> dict[str, object]:
    """When each of *tag_id*'s labels says it was applied."""
    return {row["id"]: row["tagged"] for row in list_tag_targets(tag_id)}


def test_a_rule_labels_what_its_search_matches_now(tagged) -> None:
    """The ingest case: a column added since the rule was written."""
    fresh = _add(s.catalog_column, table_id=tagged.table, name="total_net")

    applied, removed = _sync(
        rule_id=tagged.rule("totals"),
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert (applied, removed) == (2, 0)
    assert {row["id"] for row in list_tag_targets(tagged.tag)} == {
        tagged.column,
        fresh,
    }


def test_a_rule_takes_back_a_label_it_no_longer_matches(tagged) -> None:
    """A column renamed out of the search stops carrying the rule's tag."""
    rule_id = tagged.rule("totals")
    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    store().query_write(
        s.catalog_column.update()
        .where(s.catalog_column.c.id == tagged.column)
        .values(name="net_proceeds")
    )
    applied, removed = _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert (applied, removed) == (0, 1)
    assert list_tag_targets(tagged.tag) == []


def test_re_applying_an_unchanged_rule_writes_nothing(tagged) -> None:
    """Every night, for every rule: the pass has to cost nothing when nothing
    changed, or a nightly re-apply would rewrite the whole catalog's labels."""
    rule_id = tagged.rule("totals")
    targets = {TARGET_COLUMN: _columns_named("total%", tagged.table)}
    _sync(rule_id=rule_id, tag_ids=[tagged.tag], targets=targets)
    before = _tagged_dates(tagged.tag)

    assert _sync(rule_id=rule_id, tag_ids=[tagged.tag], targets=targets) == (0, 0)
    # The date, not just the count: a wipe-and-rewrite also reports one applied
    # and one removed, and would pass a test that only counted the labels left.
    assert _tagged_dates(tagged.tag) == before


def test_a_re_apply_keeps_the_day_a_surviving_label_was_applied(tagged) -> None:
    """The reason this syncs the difference instead of rebuilding the set.

    ``tagged`` is what the tag's page shows in its "Tagged" column. Deleting
    and re-inserting the row would move it to the date of the last ingest on
    every object the rule still matches.
    """
    rule_id = tagged.rule("totals")
    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )
    store().query_write(
        s.tag_target.update()
        .where(s.tag_target.c.rule_id == rule_id)
        .values(tagged=datetime(2020, 1, 1, tzinfo=timezone.utc))
    )

    _add(s.catalog_column, table_id=tagged.table, name="total_net")
    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    dates = _tagged_dates(tagged.tag)
    assert dates[tagged.column] == datetime(2020, 1, 1, tzinfo=timezone.utc)


def test_syncing_leaves_a_hand_applied_label_alone(tagged) -> None:
    """Scoped to ``rule_id``, and a person's label carries none -- so a rule
    cannot take back a label it never applied, even on an object it matched."""
    attach_tag(
        tag_id=tagged.tag,
        kind=TARGET_COLUMN,
        item_id=tagged.column,
        tagged_by="user-1",
    )

    applied, removed = _sync(
        rule_id=tagged.rule("nothing-doing"),
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("no-such-name%", tagged.table)},
    )

    assert (applied, removed) == (0, 0)
    assert tagged.items()[TARGET_COLUMN]["tagged_by"] == "user-1"


def test_another_rules_labels_are_not_touched(tagged) -> None:
    """Two rules over the same catalog, and one of them re-applying."""
    other = tagged.rule("keeps-its-own")
    attach_tags_by_rule(
        rule_id=other, tag_ids=[tagged.tag], targets=[(TARGET_TERM, tagged.term)]
    )

    _sync(
        rule_id=tagged.rule("totals"),
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert tagged.items()[TARGET_TERM]["rule"]["id"] == other


def test_a_rule_that_now_matches_nothing_takes_back_every_label(tagged) -> None:
    """An empty match is a rule that should be labelling nothing, not a rule
    to leave yesterday's labels standing for."""
    rule_id = tagged.rule("totals")
    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert _sync(rule_id=rule_id, tag_ids=[tagged.tag], targets={}) == (
        0,
        1,
    )
    assert list_tag_targets(tagged.tag) == []


def test_a_kind_dropped_from_the_rule_loses_its_labels(tagged) -> None:
    """The other way a label goes stale: the object still matches the words,
    but its kind is no longer one the rule asks for."""
    rule_id = tagged.rule("both-kinds")
    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={
            TARGET_COLUMN: _columns_named("total%", tagged.table),
            TARGET_TERM: select(s.term.c.id).where(s.term.c.id == tagged.term),
        },
    )

    _sync(
        rule_id=rule_id,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert set(tagged.items()) == {TARGET_COLUMN}


def test_a_rule_applies_every_tag_it_holds(tagged) -> None:
    """The tags travel as an array, so one statement is every tag on the kind."""
    second = create_tag(name=f"{tagged.prefix}-confidential")["id"]

    applied, _removed = _sync(
        rule_id=tagged.rule("two-tags"),
        tag_ids=[tagged.tag, second],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert applied == 2
    assert len(list_tag_targets(second)) == 1


def test_the_same_tag_twice_is_one_label(tagged) -> None:
    """The array is deduplicated before the statement sees it.

    The anti-join that keeps a re-apply cheap reads what is *stored*, so it
    cannot see a repeat inside the batch it is filtering.
    """
    applied, _removed = _sync(
        rule_id=tagged.rule("said-twice"),
        tag_ids=[tagged.tag, tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert applied == 1
    assert len(list_tag_targets(tagged.tag)) == 1


def test_a_rule_does_not_duplicate_a_tag_a_person_already_applied(tagged) -> None:
    """The label exists and stays that person's; the rule adds nothing.

    Which is why the anti-join is blind to ``rule_id``: it has to ask what the
    unique constraint asks -- whether this tag is on this object at all --
    rather than whether *this rule* put it there.
    """
    attach_tag(
        tag_id=tagged.tag,
        kind=TARGET_COLUMN,
        item_id=tagged.column,
        tagged_by="user-1",
    )

    applied, _removed = _sync(
        rule_id=tagged.rule("totals"),
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("total%", tagged.table)},
    )

    assert applied == 0
    assert tagged.items()[TARGET_COLUMN]["tagged_by"] == "user-1"


# --------------------------------------------------------------------------
# Two rules over one object, and why the replay runs in phases
# --------------------------------------------------------------------------
#
# The statements here are per rule and cannot be otherwise: `tag_target` holds
# one row per (tag, object), so the second rule to match an object writes
# nothing and the first owns the label. What that costs is only visible across
# rules -- the owner's removal takes back a label the other rule is still
# applying -- so the fix lives in
# `auto_ontology.server.rules.service.reapply_rules`, which removes for every
# rule before applying for any. These pin the halves it is built on, so a
# change down here that quietly made the phases unnecessary, or made them
# insufficient, shows up as a failure rather than as a passing suite.


def test_a_second_rule_matching_the_same_object_writes_nothing(tagged) -> None:
    """The first rule owns the row, whoever else goes on matching it."""
    owner = tagged.rule("a-owner")
    other = tagged.rule("b-other")
    matched = {TARGET_COLUMN: _columns_named("total%", tagged.table)}

    assert _sync(rule_id=owner, tag_ids=[tagged.tag], targets=matched) == (1, 0)
    assert _sync(rule_id=other, tag_ids=[tagged.tag], targets=matched) == (0, 0)
    assert tagged.items()[TARGET_COLUMN]["rule"]["id"] == owner


def test_the_owner_giving_up_takes_the_shared_label_with_it(tagged) -> None:
    """Rule by rule, the label is gone even though the other rule matches.

    This is the behaviour ``reapply_rules`` exists to order around, pinned here
    so it is visible where it happens: the removal is scoped to ``rule_id``, so
    it cannot know another rule wanted the row, and the other rule cannot have
    written one of its own.
    """
    owner = tagged.rule("a-owner")
    other = tagged.rule("b-other")
    matched = {TARGET_COLUMN: _columns_named("total%", tagged.table)}
    _sync(rule_id=owner, tag_ids=[tagged.tag], targets=matched)

    # The other rule replays first and finds nothing to do, as above. Then the
    # owner stops matching.
    _sync(rule_id=other, tag_ids=[tagged.tag], targets=matched)
    _sync(
        rule_id=owner,
        tag_ids=[tagged.tag],
        targets={TARGET_COLUMN: _columns_named("no-such%", tagged.table)},
    )

    assert list_tag_targets(tagged.tag) == []


def test_removing_first_lets_the_other_rule_take_the_label(tagged) -> None:
    """The same two rules in the order ``reapply_rules`` imposes.

    Every removal, then every application -- so the owner's row is gone before
    the rule that still matches tries to write, and the label changes hands
    inside one pass instead of disappearing until the next one.
    """
    owner = tagged.rule("a-owner")
    other = tagged.rule("b-other")
    matched = {TARGET_COLUMN: _columns_named("total%", tagged.table)}
    narrowed = {TARGET_COLUMN: _columns_named("no-such%", tagged.table)}
    _sync(rule_id=owner, tag_ids=[tagged.tag], targets=matched)

    remove_labels_no_longer_matched(rule_id=owner, targets=narrowed)
    remove_labels_no_longer_matched(rule_id=other, targets=matched)
    apply_labels_now_matched(rule_id=owner, tag_ids=[tagged.tag], targets=narrowed)
    apply_labels_now_matched(rule_id=other, tag_ids=[tagged.tag], targets=matched)

    assert tagged.items()[TARGET_COLUMN]["rule"]["id"] == other
