// SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES.
// All rights reserved.
// SPDX-License-Identifier: Apache-2.0

'use client';

import { useCallback, useState } from 'react';

import { rulesApi } from '@/api/rules';
import { Placeholders } from '@/assets/images/placeholders';
import { Button } from '@/common/Button';
import { formatDate } from '@/common/date';
import { EmptyState } from '@/common/EmptyState';
import { GlobalSearchModal } from '@/common/GlobalSearch';
import { Icon, IconName } from '@/common/icons';
import { InfiniteScroll } from '@/common/InfiniteScroll';
import { ConfirmModal, ModalCreateNewItem } from '@/common/modal';
import { PopoverMenu } from '@/common/PopoverMenu';
import { SearchInput } from '@/common/SearchInput';
import { SkeletonRows } from '@/common/Skeleton';
import { ButtonTheme, Size } from '@/enums/button';
import { EmptyStateVariant } from '@/enums/emptyState';
import { useDebouncedValue } from '@/hooks/useDebouncedValue';
import { useInfiniteList } from '@/hooks/useInfiniteList';
import { useRulesChanged } from '@/hooks/useRulesChanged';
import type { Rule } from '@/types/rules';

import { RuleInformationModal } from './RuleInformationModal';
import { RuleAuthor } from './RuleAuthor';

/** Long enough to type a word into the box. Every search in the app waits it. */
const SEARCH_DEBOUNCE_MS = 1000;

/** The radio the export form draws, which these are the only others of. */
const RADIO_CLASSNAME = 'mt-0.5 h-4 w-4 border-zinc-300 text-[#76b900] focus:ring-[#76b900]/30';

// What a delete does about the labels the rule applied. Two answers, both
// defensible, which is why it is asked rather than decided here: the labels are
// the rule still holding, or they are a classification that happens to have
// come from one and is worth keeping without it.
//
// "Delete All" leads and is the default. It is what the rule meant — a label it
// applied is a label it stands behind — and it is the choice that leaves nothing
// behind to explain, which is the safer of the two to arrive at by pressing
// Enter.
//
// Kept labels are attributed to whoever wrote the rule, which is worth saying
// in the option: the tag's page will show a person against objects nobody
// visited, and a reader should know that came from here.
const DELETE_OPTIONS = [
	{
		keepTags: false,
		label: 'Delete All',
		description:
			'Delete the rule and remove all tags from their associated objects that were generated by this rule. A tag left labelling nothing, and applied by no other rule, is deleted with it.',
	},
	{
		keepTags: true,
		label: 'Delete Rule Only',
		description:
			'Delete the rule but keep all tags on their associated objects that were generated by this rule. Those tags are then attributed to whoever created the rule.',
	},
];

/**
 * Rules are not authored here: they are built from a global search, over the
 * items the search returns. So this screen only lists them, and the search is
 * offered from the empty state alone — a create button on a page with results
 * of its own would have nothing to create a rule over.
 *
 * A card per rule, and deliberately not a link. A rule has no page of its own
 * to open: what it applies is already on the card, and the rest of it — the
 * search it replays and the filters that search carried — is a dialog rather
 * than a screen. Everything clickable on a card is a control that says what it
 * does.
 *
 * Renaming is the only edit a rule takes, from the card's own menu. What a rule
 * matches is what it *is*, so changing that is a new rule rather than an edit of
 * this one — a name is only how this list refers to it.
 *
 * Deleting is the one destructive thing here, and it reaches further than the
 * card: the labels the rule applied are its to take back. So it asks first, and
 * asks about them rather than only about the rule — either they go with it, or
 * they stay on the objects they are on with nothing left to explain them.
 *
 * The list is paged and read as it is scrolled, and the box at the top searches
 * *the rules*, not the catalog. Both are the terms page's arrangement, and for
 * the same reason: with a page at a time on screen, a filter applied to the
 * rows already loaded would answer from a fraction of the list, so the query
 * goes to the backend and starts the paging over.
 */
export default function RulesSettingsPage() {
	const [searchOpen, setSearchOpen] = useState(false);
	const [information, setInformation] = useState<Rule | null>(null);
	const [renaming, setRenaming] = useState<Rule | null>(null);
	const [name, setName] = useState('');
	const [renameError, setRenameError] = useState<string | null>(null);
	const [renamingSaving, setRenamingSaving] = useState(false);
	const [confirmDelete, setConfirmDelete] = useState<Rule | null>(null);
	const [keepTags, setKeepTags] = useState(false);
	const [deleting, setDeleting] = useState(false);
	const [deleteError, setDeleteError] = useState<string | null>(null);
	const [query, setQuery] = useState('');
	const debouncedQuery = useDebouncedValue(query.trim(), SEARCH_DEBOUNCE_MS);
	// Whether a first page has ever landed, so the box is not drawn over a list
	// that has not arrived and then withdrawn when it turns out to be empty.
	const [hasLoaded, setHasLoaded] = useState(false);

	const fetchRulesPage = useCallback(
		async (skip: number, limit: number) => {
			const response = await rulesApi.getAll({
				...(debouncedQuery ? { query: debouncedQuery } : {}),
				skip,
				limit,
			});
			setHasLoaded(true);
			if (response.error) return { error: response.message ?? 'Failed to load rules.' };
			return { items: response.data ?? [], total: response.total ?? 0 };
		},
		[debouncedQuery],
	);

	const {
		items: rules,
		isLoading: loading,
		isLoadingMore,
		error,
		hasMore,
		loadMore,
		reload,
	} = useInfiniteList(fetchRulesPage, { itemKey: (rule) => rule.id });

	// A rule is created in the search dialog, and the answer is an id alone — so
	// the card it added is read back from the first page rather than assembled
	// from what was posted.
	//
	// Announced rather than handled on close, because the dialog that saved it
	// is as often the top bar's as this page's: with rules on screen this page
	// offers no create button, so the top bar is the way to add a second one.
	useRulesChanged(reload);

	const trimmedName = name.trim();
	// Nothing to save when the name is blank or is the one the rule already has:
	// an empty rename is a 400, and an unchanged one would advance `modified` and
	// record an editor for an edit that did not happen.
	const canRename = !renamingSaving && trimmedName.length > 0 && trimmedName !== renaming?.name;

	const openRename = (rule: Rule) => {
		setRenameError(null);
		setName(rule.name);
		setRenaming(rule);
	};

	const closeRename = () => {
		if (renamingSaving) return;
		setRenaming(null);
		setRenameError(null);
	};

	const handleRename = async () => {
		if (renaming == null || !canRename) return;
		setRenamingSaving(true);
		setRenameError(null);

		const response = await rulesApi.update(renaming.id, { name: trimmedName });
		setRenamingSaving(false);

		if (response.error) {
			setRenameError(response.message ?? 'Failed to rename rule.');
			return;
		}

		setRenaming(null);
		// Re-read rather than write the new name into the card, even though the
		// answer carries the whole rule: the list is ordered by name, so a renamed
		// rule generally belongs somewhere else in it, and patching the row in
		// place would leave it sorted by a name it no longer has.
		reload();
	};

	const handleConfirmDelete = async () => {
		if (confirmDelete == null) return;
		setDeleting(true);
		setDeleteError(null);

		const response = await rulesApi.delete(confirmDelete.id, { keepTags });
		setDeleting(false);

		if (response.error) {
			setDeleteError(response.message ?? 'Failed to delete rule.');
			return;
		}

		setConfirmDelete(null);
		// Re-read rather than drop the card locally: the delete changed how many
		// rules there are, and the pages already loaded were windows on the old
		// count — keeping them would leave the list one row short of every
		// window boundary it has passed.
		reload();
	};

	return (
		<main className="flex min-h-0 min-w-0 flex-1 flex-col bg-[linear-gradient(180deg,rgba(255,255,255,1)_0%,rgba(250,250,250,0.6)_100%)] dark:bg-[linear-gradient(180deg,rgba(9,9,11,1)_0%,rgba(24,24,27,0.5)_100%)]">
			<InfiniteScroll
				className="flex-1 px-7 py-6 sm:px-10 sm:py-7"
				onLoadMore={loadMore}
				isLoading={isLoadingMore}
				hasMore={hasMore}
				// Only a failed *first* page is rendered below — a failed later page
				// keeps the cards already loaded and gets its own retry control.
				error={rules.length > 0 ? error : null}
			>
				<div className="w-full space-y-5">
					<h1 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
						Rules
					</h1>

					{/* A box for narrowing a list, so there is none until there is a
					    list: the empty state is a page about making the first rule,
					    and a search over nothing is one more control to read past.
					    It survives a query that matches nothing, though — that list
					    is empty *because* of the box, and taking it away would leave
					    no way to clear the query and get the rules back. */}
					{hasLoaded && (rules.length > 0 || debouncedQuery !== '') ? (
						<SearchInput
							value={query}
							onChange={setQuery}
							placeholder="Search rules…"
							aria-label="Search rules"
							className="w-full"
						/>
					) : null}

					{!loading && error != null && rules.length === 0 ? (
						<div className="rounded-lg border border-red-200/90 bg-red-50 px-4 py-3 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/40 dark:text-red-200">
							{error}
						</div>
					) : null}

					{loading ? (
						<div className="py-2" role="status" aria-label="Loading rules">
							<SkeletonRows rows={4} />
						</div>
					) : null}

					{!loading && error == null && rules.length === 0 ? (
						<EmptyState
							variant={EmptyStateVariant.Dashed}
							illustration={<Placeholders.NoRules />}
							title={
								debouncedQuery
									? 'No Rules Match Your Search'
									: 'No Rules Created Yet'
							}
							description={
								debouncedQuery
									? undefined
									: 'Rules are created from the global search. Search for the items you would like to tag, then create a new rule from the results.'
							}
							action={
								debouncedQuery
									? undefined
									: {
											label: 'Open Global Search',
											onClick: () => setSearchOpen(true),
										}
							}
						/>
					) : null}

					{rules.length > 0 ? (
						<ul className="space-y-3">
							{rules.map((rule) => (
								<li
									key={rule.id}
									className="rounded-lg border border-zinc-200/90 bg-white/90 shadow-sm ring-1 ring-zinc-950/[0.04] dark:border-zinc-700/90 dark:bg-zinc-950/50 dark:ring-white/[0.06]"
								>
									<div className="flex items-center gap-2 px-4 py-3">
										<Icon
											name={IconName.Lightning}
											className="h-4 w-4 shrink-0 text-[#76b900]"
										/>
										<span className="min-w-0 flex-1 truncate text-sm font-semibold text-zinc-900 dark:text-zinc-100">
											{rule.name}
										</span>
										<div className="relative w-[26px] shrink-0">
											<PopoverMenu
												items={[
													{
														label: 'Information',
														icon: (
															<Icon
																name={IconName.Exploration}
																className="h-3.5 w-3.5"
															/>
														),
														onClick: () => setInformation(rule),
													},
													{
														label: 'Rename Rule',
														icon: (
															<Icon
																name={IconName.Pencil}
																className="h-3.5 w-3.5"
															/>
														),
														onClick: () => openRename(rule),
													},
													{
														label: 'Delete Rule',
														icon: (
															<Icon
																name={IconName.Trash}
																className="h-3.5 w-3.5"
															/>
														),
														onClick: () => {
															setDeleteError(null);
															// Back to the default, so the
															// choice made about one rule is
															// not inherited by the next.
															setKeepTags(false);
															setConfirmDelete(rule);
														},
														danger: true,
													},
												]}
												trigger={({ toggle }) => (
													<Button
														theme={ButtonTheme.IconNeutral}
														size={Size.SMALL}
														iconOnly
														type="button"
														onClick={toggle}
														aria-label={`Actions for ${rule.name}`}
													>
														<Icon
															name={IconName.DotsVertical}
															className="h-4 w-4"
														/>
													</Button>
												)}
											/>
										</div>
									</div>
									<div className="flex flex-wrap items-center gap-x-3 gap-y-2 border-t border-zinc-200/90 px-4 py-2.5 text-xs text-zinc-500 dark:border-zinc-700/90 dark:text-zinc-400">
										<Icon
											name={IconName.Users}
											className="h-3.5 w-3.5 shrink-0"
										/>
										<span>Created By</span>
										<RuleAuthor author={rule.created_by_user} />
										<span className="ml-auto flex items-center gap-3">
											<span>Last Modified</span>
											<span className="text-zinc-600 dark:text-zinc-300">
												{formatDate(rule.modified)}
											</span>
										</span>
									</div>
								</li>
							))}
						</ul>
					) : null}
				</div>
			</InfiniteScroll>

			<RuleInformationModal rule={information} onClose={() => setInformation(null)} />

			{/* No length cap on the input, unlike the tag dialog: the backend holds a
			    rule name to nothing but "not blank", so a limit enforced only here
			    would be one nothing else agrees with. */}
			<ModalCreateNewItem
				open={renaming !== null}
				onClose={closeRename}
				title="Rename Rule"
				submitLabel={renamingSaving ? 'Saving…' : 'Save'}
				canSubmit={canRename}
				onSubmit={handleRename}
				className="w-[520px] max-w-full"
			>
				<div>
					<label
						htmlFor="rule-name"
						className="mb-1.5 flex items-center gap-2 text-sm font-semibold text-zinc-900 dark:text-zinc-100"
					>
						<Icon
							name={IconName.Lightning}
							className="h-4 w-4 text-zinc-500 dark:text-zinc-400"
						/>
						Rule Name
					</label>
					<input
						id="rule-name"
						type="text"
						value={name}
						onChange={(event) => setName(event.target.value)}
						placeholder="Type rule name"
						className="w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-700 outline-none transition-colors placeholder:text-zinc-400 focus:border-[#76b900] focus:ring-2 focus:ring-[#76b900]/30 dark:border-zinc-600 dark:bg-zinc-900 dark:text-zinc-300 dark:placeholder:text-zinc-500"
					/>
					{/* The tags and the search are on the information card, and are not
					    editable — worth saying inside the dialog that changes the one
					    thing about a rule that is. */}
					<p className="mt-1.5 text-xs text-zinc-500 dark:text-zinc-400">
						Renaming does not change what the rule matches or the tags it applies.
					</p>
				</div>

				{renameError ? (
					<div className="rounded-lg border border-red-200/90 bg-red-50 px-3 py-2 text-xs text-red-800 dark:border-red-900/50 dark:bg-red-950/40 dark:text-red-200">
						{renameError}
					</div>
				) : null}

				{/* Footer rule, as the tag dialog has: the negative margins cancel the
				    body's padding so it spans the modal. */}
				<div className="-mx-6 border-t border-zinc-200 dark:border-zinc-700" />
			</ModalCreateNewItem>

			{/* The tags are the part worth asking about: they are on objects nobody
			    visited, and deleting the rule is what would take them off — so a
			    reader who thinks they are only removing a row from this list
			    should be shown the wider reach before confirming, not after, and
			    given the choice of whether to accept it. */}
			<ConfirmModal
				open={confirmDelete !== null}
				title="Delete rule"
				className="w-[520px] max-w-full"
				message={
					confirmDelete == null ? (
						''
					) : (
						<>
							<p>{`Are you sure you want to delete "${confirmDelete.name}"? This action cannot be undone.`}</p>
							<fieldset className="mt-4">
								<legend className="text-xs font-medium text-zinc-800 dark:text-zinc-200">
									The tags this rule applied
								</legend>
								<div className="mt-2 space-y-2">
									{DELETE_OPTIONS.map((option) => (
										<label
											key={option.label}
											className="flex cursor-pointer items-start gap-2 rounded-lg border border-zinc-200 px-3 py-2 hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800/80"
										>
											<input
												type="radio"
												name="rule-delete-scope"
												checked={keepTags === option.keepTags}
												onChange={() => setKeepTags(option.keepTags)}
												disabled={deleting}
												className={RADIO_CLASSNAME}
											/>
											<span>
												<span className="block text-sm font-medium text-zinc-900 dark:text-zinc-100">
													{option.label}
												</span>
												<span className="block text-xs text-zinc-500 dark:text-zinc-400">
													{option.description}
												</span>
											</span>
										</label>
									))}
								</div>
							</fieldset>
						</>
					)
				}
				// The button says which of the two is about to happen, so the last
				// thing read before pressing it is the choice that was made.
				confirmLabel={keepTags ? 'Delete Rule Only' : 'Delete All'}
				onConfirm={handleConfirmDelete}
				onCancel={() => {
					if (deleting) return;
					setConfirmDelete(null);
					setDeleteError(null);
				}}
				confirming={deleting}
				error={deleteError}
			/>

			<GlobalSearchModal open={searchOpen} onClose={() => setSearchOpen(false)} />
		</main>
	);
}
