# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

packages:
    - '.'
onlyBuiltDependencies:
    - '@prisma/engines'
    - prisma
    - sharp
    - unrs-resolver
