# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""The relational schema: SQLAlchemy Core table metadata, no ORM.

Alembic autogenerates migrations by diffing against :data:`METADATA`, so this
file is the single source of truth for the schema — never hand-edit a migration
that has already been applied.

Three decisions shape everything downstream:

* **Containment is a parent foreign key, not an edge table.** A database owns
  its schemas, a schema its tables, a table its columns. That is what makes
  deleting a database one statement, with ``ON DELETE CASCADE`` doing the rest.
* **Ids are ``text`` uuids**, defaulted by ``gen_random_uuid()::text``. Not
  ``uuid``: every DAL signature is ``id: str``, and a malformed id arriving from
  a URL should yield an empty result rather than a ``22P02`` 500. Not integers:
  ids are consumed as opaque strings by the vector-store row key, the frontend's
  pipe-separated focus param, and ``model_interchange``'s ``imported_id OR id``
  match.
* **The catalog tier is prefixed ``catalog_``** — one rule that sidesteps
  ``table`` and ``column`` being reserved words and ``schema`` colliding with
  ``information_schema``, instead of three separate exceptions.
"""

from __future__ import annotations

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import JSONB


#: The two terminal outcomes of a semantic compilation pass, for the check
#: constraint on :data:`semantic_compilation_history` below.
#:
#: Defined here rather than in ``gsf.ingestion_service.history``, which writes
#: them: they are part of the column's definition, and the module that writes
#: the values importing them from the constraint that permits them is the only
#: arrangement in which the two cannot disagree.
RUN_SUCCEEDED = "succeeded"
RUN_FAILED = "failed"

#: Naming convention so autogenerated constraints get stable, readable names.
#: Without it Alembic emits server-assigned names that differ between databases
#: and make a downgrade unable to find what it is dropping.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# No ``schema=`` on purpose.
# Naming the default schema explicitly makes autogenerate emit permanent drift:
# metadata reports ``referent_schema='public'`` for every foreign key while
# reflection reports the default schema as ``None``, so Alembic sees 33 changed
# constraints and proposes dropping and recreating all of them, on every run,
# forever. Leaving it unset makes both sides agree. Placement is guaranteed by
# the ``search_path`` pinned on every connection (see ``gsf/dal/session.py``),
# not by luck.
METADATA = MetaData(naming_convention=NAMING_CONVENTION)

#: ``gen_random_uuid()`` is built into Postgres from 13; no pgcrypto needed.
#:
#: Parenthesised to match how Postgres *stores* the expression. Written as
#: ``gen_random_uuid()::text`` it produces identical DDL, but the catalog reads
#: back ``(gen_random_uuid())::text``, and ``alembic check`` — which compares
#: server defaults as text — then reports drift on all 14 id columns on a
#: database that is perfectly up to date. Matching the normalised form keeps
#: the drift check meaningful instead of turning off ``compare_server_default``.
_UUID_DEFAULT = text("(gen_random_uuid())::text")


def _id() -> Column:
    return Column("id", Text, primary_key=True, server_default=_UUID_DEFAULT)


def _imported_id() -> Column:
    """Id carried over from a model-interchange export.

    ``_resolve_entities_batch`` matches YAML ids against ``imported_id OR id``,
    so an id from a previous export can arrive as an *imported* id on a node
    whose own id is different. Non-unique: two databases can legitimately import
    the same source model.
    """
    return Column("imported_id", Text, nullable=True)


def _certified(name: str) -> Column:
    """A human-set certification flag.

    ``NOT NULL DEFAULT false`` rather than nullable, because every read of these
    absent means false, and making that the column's job removes the coalesce
    from each caller — and, more usefully, the chance of one forgetting it.
    """
    return Column(name, Boolean, nullable=False, server_default=text("false"))


# ---------------------------------------------------------------------------
# Catalog tier — Database -> Schema -> Table -> Column
# ---------------------------------------------------------------------------

catalog_database = Table(
    "catalog_database",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    # UI-managed connection form. Stored here only when Vault is not configured;
    # with Vault the credentials live there and this stays null (the database
    # name is the lookup key -- there is no separate reference field).
    Column("connection", JSONB, nullable=True),
    Column("dialect", Text, nullable=True),
    # A database and a schema each carry a curated description, as tables and
    # columns do. Without them `patch_catalog_node` silently dropped the write
    # and still answered 200, so the UI reported success and the text was gone
    # on reload.
    Column("description", Text, nullable=True),
    _certified("description_certified"),
    _imported_id(),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("pulled", DateTime(timezone=True), nullable=True),
)

catalog_schema = Table(
    "catalog_schema",
    METADATA,
    _id(),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _certified("description_certified"),
    _imported_id(),
    UniqueConstraint("database_id", "name", name="uq_catalog_schema_database_name"),
)

#: Dimensionality of the embedding model (`nvidia/llama-nemotron-embed-vl-1b-v2`).
#: Not a tuning knob -- it is what the model emits, and a column declared at any
#: other width rejects every insert.
EMBEDDING_DIMENSIONS = 2048


#: Columns that exist for vector search and are never part of an entity's
#: user-facing properties. `select(table)` returns every column, so any read
#: that means "all of this node's properties" has to subtract these -- otherwise
#: a node-detail API response carries 2048 floats (~8KB) per row.
INTERNAL_COLUMNS = frozenset(
    {
        "embedding",
        "embedding_text",
        "embedding_database_name",
        "embedding_metadata",
    }
)


def public_columns(table) -> list:
    """Every column of *table* except the vector-search internals."""
    return [c for c in table.c if c.name not in INTERNAL_COLUMNS]


def _embedding_columns() -> tuple[Column, ...]:
    """Vector-search columns, carried by every embeddable entity.

    These live on the entity itself rather than in a side table, which is what
    makes an embedding subject to the same ``ON DELETE CASCADE`` as the row it
    describes. The previous arrangement -- a separate collection keyed by an id
    in a JSON blob -- had no such link, so deleting a catalog row orphaned its
    vector, and retrieval kept scoring rows that no longer existed.

    All three are nullable: a row exists before it is embedded, and "not yet
    embedded" has to be representable. ``embedding IS NULL`` is the re-embed
    work queue.

    ``embedding_database_name`` is denormalised on purpose. It is the filter
    every search applies, and the relational path to it is three joins deep from
    a column (``catalog_column -> catalog_table -> catalog_schema ->
    catalog_database``) and undefined for a Term or a CustomAnalysis, which are
    not owned by one database at all.
    """
    return (
        Column("embedding", Vector(EMBEDDING_DIMENSIONS), nullable=True),
        # The exact text that was embedded, returned with every hit as ``text``.
        # Not decorative: ``generate_sql`` concatenates it into the prompt the
        # model sees, so this is the description the LLM reasons over.
        #
        # Stored rather than re-rendered from the row on read. The renderer
        # composes a table with all of its columns, so deriving it would mean a
        # join plus an aggregation per hit -- and, more importantly, a freshly
        # rendered string describes the entity *now*, while the vector describes
        # it as of the last embed. Keeping the text that actually produced the
        # vector means a hit's explanation always matches why it matched.
        Column("embedding_text", Text, nullable=True),
        Column("embedding_database_name", Text, nullable=True),
        # Whatever else the producer attached to the embedded record.
        #
        # The old collection stored arbitrary metadata in a JSON column, and
        # callers rely on it: semantic FK inference filters candidates on
        # `is_unique` and reads `table_id` / `source_column` back off each hit.
        # Promoting those to real columns would work until the next field is
        # added -- which is exactly what happened while this was being written --
        # so the general shape is kept.
        #
        # `id`, `label` and `database_name` are deliberately *not* duplicated in
        # here: those have real columns, and two copies of an identifier is one
        # too many.
        Column("embedding_metadata", JSONB, nullable=True),
    )


catalog_table = Table(
    "catalog_table",
    METADATA,
    _id(),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    # Set from the UI's certification checkbox, via patch_catalog_node. Easy to
    # miss, because nothing in the ingest ever writes it
    # -- it only appears once a human certifies a description. Without the
    # column the PATCH still returns 200 and the checkbox still ticks; the flag
    # is simply dropped on the way in and reads back false forever.
    _certified("description_certified"),
    # Primary key column names. A list on the node today, so a text[] here
    # rather than a join table -- nothing ever queries "which tables have this
    # pk column", and a join table would make every read a second query.
    Column("pk", ARRAY(Text), nullable=True),
    Column("table_type", Text, nullable=True),
    _imported_id(),
    UniqueConstraint("schema_id", "name", name="uq_catalog_table_schema_name"),
    *_embedding_columns(),
)

catalog_column = Table(
    "catalog_column",
    METADATA,
    _id(),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    # As on catalog_table: written only by the UI's certification checkbox.
    _certified("description_certified"),
    Column("data_type", Text, nullable=True),
    # A JSON string, read back as a string by callers. Promoting it to jsonb is
    # a deliberate follow-up with its consumers updated, not a free change.
    Column("sample_values", Text, nullable=True),
    # How the values are *written*, not what they are: 'YYMMDD', 'YYYY-MM-DD'.
    # Generic storage notation despite only date inference filling it today
    # (`gsf.semantic.date_format`) -- an address or id profiler would write the
    # same field. `data_type`/`name`/`description` say what the values mean.
    #
    # It exists because date columns are held out of sample-value profiling, so
    # nothing else in the prompt tells the model what form to compare against:
    # `950324` and `1995-03-24` are the same day and share no predicate, and a
    # wrong guess yields SQL that runs, returns nothing, and looks right.
    Column("format", Text, nullable=True),
    Column("is_unique", Boolean, nullable=True),
    # A real Boolean. It used to hold the *strings* `information_schema`
    # reports, 'YES' and 'NO', which read back as truthy either way -- so
    # `bool(stored)` was True for every column and every export claimed the
    # whole catalog was nullable. Connectors now convert at their own edge
    # (see `gsf.connectors.base.SQLDatabase.get_columns`) and NULL still means
    # "the connector could not determine it", which callers treat as nullable.
    Column("is_nullable", Boolean, nullable=True),
    # A genuine integer, despite the parser handing the write path a string --
    # something coerces on the way in.
    Column("ordinal_position", Integer, nullable=True),
    _imported_id(),
    UniqueConstraint("table_id", "name", name="uq_catalog_column_table_name"),
    *_embedding_columns(),
)

# FOREIGN_KEY: Column -> Column.
column_foreign_key = Table(
    "column_foreign_key",
    METADATA,
    Column(
        "source_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    # Stamped by every ingest, then used to delete the keys this run did not
    # see -- the source database may have dropped a constraint. Without it
    # there is no way to tell a removed foreign key from one simply not
    # re-asserted, and stale keys would accumulate forever.
    Column("last_seen", DateTime(timezone=True), nullable=True),
)


# JOIN / UNION: Column <-> Column, carrying the statements that observed them.
#
# Distinct from `table_join` below, and both are real. This one is written by
# **query** ingestion -- `sql_parse` emits one entry per observed join
# condition, so `refs` accumulates `"<sql id>|<condition>"` strings as more
# statements are seen. `table_join` is written only by a model import and
# carries the join's *columns*; nothing writes both.
#
# `refs` is an array that grows rather than a row per reference, because that is
# what the readers expect. A row per ref would be the better model and is a deliberate follow-up,
# not a porting decision.
def _column_pair_edge(name: str) -> Table:
    return Table(
        name,
        METADATA,
        Column(
            "source_column_id",
            Text,
            ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
            primary_key=True,
        ),
        Column(
            "target_column_id",
            Text,
            ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
            primary_key=True,
        ),
        Column("refs", ARRAY(Text), nullable=False, server_default=text("'{}'")),
    )


column_join = _column_pair_edge("column_join")
column_union = _column_pair_edge("column_union")


# JOIN: Table -> Table, carrying the columns that join them.
table_join = Table(
    "table_join",
    METADATA,
    Column(
        "source_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("join_columns", JSONB, nullable=True),
)

# ---------------------------------------------------------------------------
# SQL statements and their table references
# ---------------------------------------------------------------------------

sql_query = Table(
    "sql_query",
    METADATA,
    _id(),
    Column("sql_full_query", Text, nullable=False),
    Column("query_count", Integer, nullable=False, server_default=text("0")),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("last_seen", DateTime(timezone=True), nullable=True),
    # How many times this statement has been observed, all time. The graph also
    # carried a `count_{month}_{year}` property per month, which is not
    # reproduced: no reader has ever been able to parse those names (they are
    # matched against `count_monthly_YYYY_MM`), so they hold no information
    # anything can use. See DECISIONS.md record 007.
    Column("total_counter", Integer, nullable=False, server_default=text("0")),
    Column("last_query_timestamp", DateTime(timezone=True), nullable=True),
    # Structural fingerprint, used to pre-filter candidates before the
    # expensive sqlglot comparison in query deduplication.
    Column("nodes_count", Integer, nullable=True),
    Column("join_count", Integer, nullable=False, server_default=text("0")),
    Column("union_count", Integer, nullable=False, server_default=text("0")),
    # model_interchange matches a Sql node by its *text*
    # (match_props={"sql_full_query": sql}). Statement text can exceed the btree
    # row limit, so the uniqueness is enforced on a hash rather than the column.
    Index(
        "uq_sql_query_text_md5",
        func.md5(text("sql_full_query")),
        unique=True,
    ),
)

# SQL: Sql -> Table. An association, because one statement references many
# tables and one table is referenced by many statements.
sql_query_table = Table(
    "sql_query_table",
    METADATA,
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# SQL: Sql -> Column. The same relationship type, pointing at the leaf columns a
# statement selects. Two tables rather than one polymorphic association, because
# the two are always read separately -- `load_sqls_to_tables` returns tables and
# columns as distinct lists, and query deduplication compares them as distinct
# sets.
sql_query_column = Table(
    "sql_query_column",
    METADATA,
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# ---------------------------------------------------------------------------
# Semantic tier
# ---------------------------------------------------------------------------

term = Table(
    "term",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("synonyms", ARRAY(Text), nullable=True),
    _certified("name_certified"),
    _certified("description_certified"),
    _imported_id(),
    UniqueConstraint("name", "source", name="uq_term_name_source"),
    *_embedding_columns(),
)

# REPRESENTS: Table -> Term.
table_term = Table(
    "table_term",
    METADATA,
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

column_attribute = Table(
    "column_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("datatype", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("source_column", Text, nullable=False),
    Column("term_name", Text, nullable=False),
    # Deliberately NOT a foreign key, and deliberately not nullable. The
    # importer legitimately writes '' when col_ctx is missing
    # (model_interchange.py:1260), and this is compared as a plain string in
    # `ca.table_id IN $table_ids`. An FK here would reject valid imports.
    Column("table_id", Text, nullable=False),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    # The 5-part merge key, exactly as merge_column_attribute matches on.
    UniqueConstraint(
        "name",
        "source_column",
        "term_name",
        "table_id",
        "source",
        name="uq_column_attribute_merge_key",
    ),
    *_embedding_columns(),
)

# PROPERTY_OF: ColumnAttribute -> Term.
column_attribute_term = Table(
    "column_attribute_term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

# HAS_ATTRIBUTE and SEMANTIC_FK both run Column -> ColumnAttribute, but they
# assert different things and get their own tables rather than one table with a
# `kind` discriminator:
#
#   HAS_ATTRIBUTE  this column *is* an instance of the attribute
#   SEMANTIC_FK    this column *references* the attribute, which describes a
#                  column on another table
#
# Their cardinality already differs -- `resolve_semantic_fks` treats a column as
# unlinked when it has no SEMANTIC_FK, so at most one is expected, whereas a
# column can carry several attributes -- and a discriminator in the primary key
# makes any constraint that applies to only one of them impossible to express.
column_has_attribute = Table(
    "column_has_attribute",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

column_semantic_fk = Table(
    "column_semantic_fk",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

sql_attribute = Table(
    "sql_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    Column("expression", Text, nullable=True),
    Column("source", Text, nullable=True),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    CheckConstraint(
        "source IS NULL OR source IN ('manual', 'sql', 'table', 'bridgeTable')",
        name="source_value",
    ),
    *_embedding_columns(),
)

# PROPERTY_OF: SqlAttribute -> Term.
sql_attribute_term = Table(
    "sql_attribute_term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

# HAS_SQL: SqlAttribute -> Sql.
sql_attribute_sql = Table(
    "sql_attribute_sql",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

custom_analysis = Table(
    "custom_analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    _imported_id(),
    *_embedding_columns(),
)

# HAS_SQL: CustomAnalysis -> Sql.
custom_analysis_sql = Table(
    "custom_analysis_sql",
    METADATA,
    Column(
        "analysis_id",
        Text,
        ForeignKey(custom_analysis.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# Never attached to a database, which is why a *scoped* semantic reset does not
# reach these -- see `reset.delete_semantic_layer`.
pql_analysis = Table(
    "pql_analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("pql", Text, nullable=True),
    _imported_id(),
    *_embedding_columns(),
)

# Declared in gsf/semantic/constants.py and referenced by reset.py's
# _SEMANTIC_LABELS, but never written by GSF today. Created so the reset
# cascade has something to point at and so a future writer needs no migration.
text_attribute = Table(
    "text_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

analysis = Table(
    "analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

# ---------------------------------------------------------------------------
# Zones
# ---------------------------------------------------------------------------

zone = Table(
    "zone",
    METADATA,
    _id(),
    # Deliberately **not** unique. The rule the application enforces is neither
    # what a plain UNIQUE gives you nor a stricter version of it:
    #
    #   * it is case-insensitive on the *trimmed* name, so a UNIQUE column would
    #     admit "Sales" alongside "sales", which the application rejects; and
    #   * it is scoped to zones sharing a database with the zone's items, so a
    #     UNIQUE column would reject the same zone name in two unrelated
    #     databases, which the application allows.
    #
    # A constraint that is wrong in both directions is worse than none. The
    # check stays in application code, exactly as today. Making it a database
    # constraint would mean a partial index on `lower(trim(name))` *per
    # database*, which zone membership -- being many-to-many through
    # zone_target -- cannot express.
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("color", Text, nullable=True),
    # A disabled zone still exists and is still administrable; it just grants
    # nothing. A boolean rather than a separate table so every read says
    # `enabled` once instead of unioning two sources.
    Column("enabled", Boolean, nullable=False, server_default=text("true")),
)

# ZONE_OF is polymorphic: a zone can target a Database, a Schema or a Table.
# Three nullable FKs with a CHECK beats a (kind, id) pair because it keeps real
# referential integrity and lets a deleted table remove its zone membership by
# cascade -- a (kind, id) pair cannot have an FK at all, and would leave
# dangling grants behind, which is an access-control bug rather than untidiness.
zone_target = Table(
    "zone_target",
    METADATA,
    _id(),
    Column("zone_id", Text, ForeignKey(zone.c.id, ondelete="CASCADE"), nullable=False),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    CheckConstraint(
        "num_nonnulls(database_id, schema_id, table_id) = 1",
        name="exactly_one_target",
    ),
)

# ---------------------------------------------------------------------------
# Service bookkeeping
# ---------------------------------------------------------------------------

# One row per semantic compilation pass, written by the ingestion service (see
# `gsf.ingestion_service.history`) and read back by the settings page.
#
# It arrived creating itself at service startup instead of through a migration.
# That is why it is worth a note: a `public` table this schema does not declare
# is indistinguishable from one deleted from the model, so autogenerate emitted
# `drop_table` for it on every run -- exactly what `include_object` in
# `alembic/env.py` warns a stray table invites.
semantic_compilation_history = Table(
    "semantic_compilation_history",
    METADATA,
    # BIGSERIAL, unlike the Text uuids everywhere else here: rows are appended
    # in time order by one writer and read back "most recent first", which an
    # ascending integer answers directly.
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    # NULL until the pass reaches a terminal outcome -- which it never does if
    # it was stopped, disabled mid-run, or killed. See `history.py` on why an
    # unfinished pass is left this way rather than given an "aborted" status.
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("status", Text, nullable=True),
    CheckConstraint(
        f"status IS NULL OR status IN ('{RUN_SUCCEEDED}', '{RUN_FAILED}')",
        name="status_value",
    ),
)


# ---------------------------------------------------------------------------
# Indexes for the read paths
# ---------------------------------------------------------------------------

Index("ix_catalog_schema_database_id", catalog_schema.c.database_id)
Index("ix_catalog_table_schema_id", catalog_table.c.schema_id)
Index("ix_catalog_table_name", catalog_table.c.name)
Index("ix_catalog_column_table_id", catalog_column.c.table_id)
Index("ix_catalog_column_name", catalog_column.c.name)

Index("ix_column_foreign_key_target", column_foreign_key.c.target_column_id)
Index("ix_table_join_target", table_join.c.target_table_id)
Index("ix_sql_query_table_table_id", sql_query_table.c.table_id)
Index("ix_sql_query_column_column_id", sql_query_column.c.column_id)

Index("ix_term_name", term.c.name)
Index("ix_table_term_term_id", table_term.c.term_id)
Index("ix_column_attribute_term_name", column_attribute.c.term_name)
Index("ix_column_attribute_table_id", column_attribute.c.table_id)
Index("ix_column_attribute_term_term_id", column_attribute_term.c.term_id)
Index("ix_sql_attribute_term_term_id", sql_attribute_term.c.term_id)

# Both link tables are read in both directions -- from a column to its
# attributes, and from an attribute back to the columns that reference it
# (`fetch_attr_column_contexts` binds the attribute first). The composite
# primary key already indexes the column_id order; these cover the reverse.
Index("ix_column_has_attribute_attribute_id", column_has_attribute.c.attribute_id)
Index("ix_column_semantic_fk_attribute_id", column_semantic_fk.c.attribute_id)

# Supports the case-insensitive name check that replaces a unique constraint.
Index("ix_zone_name_lower", func.lower(zone.c.name))
Index("ix_zone_target_zone_id", zone_target.c.zone_id)
Index("ix_zone_target_database_id", zone_target.c.database_id)
Index("ix_zone_target_schema_id", zone_target.c.schema_id)
Index("ix_zone_target_table_id", zone_target.c.table_id)

# imported_id is matched alongside id during model import; non-unique.
for _table in (
    catalog_database,
    catalog_schema,
    catalog_table,
    catalog_column,
    term,
    column_attribute,
    sql_attribute,
    custom_analysis,
):
    Index(f"ix_{_table.name}_imported_id", _table.c.imported_id)

# ---------------------------------------------------------------------------
# join_path_edge view -- the traversal surface for find_join_path ONLY
# ---------------------------------------------------------------------------

#: Edge set for :func:`gsf.dal.attributes.find_join_path`, and **nothing else**.
#: Named for that function rather than generically, because its contents are
#: shaped by that one traversal's rules and are wrong for any other:
#:
#: * ``CONTAINS`` (Table <-> Column) and ``HAS_ATTRIBUTE``
#:   (Column <-> ColumnAttribute) appear in both directions.
#: * ``SEMANTIC_FK`` appears **outgoing only** (Column -> ColumnAttribute).
#:
#: Note carefully what that last line does *not* say. ``SEMANTIC_FK`` is
#: **stored** in one direction, but the codebase reads it in both:
#: ``fetch_attr_column_contexts`` binds a ColumnAttribute and finds the columns
#: referencing it, which is the reverse traversal. Anything needing that must
#: query :data:`column_semantic_fk` directly rather than this view.
#:
#: The restriction is specific to path-finding. Allowed to traverse SEMANTIC_FK
#: backwards, a path would hop from one FK column up to a shared target
#: attribute and back down a *different* FK column, inventing a join between two
#: columns that merely reference the same thing -- two ``customer_id`` columns
#: joined to each other. Here that is simply a row the view does not emit.
JOIN_PATH_EDGE_VIEW_SQL = """
CREATE OR REPLACE VIEW join_path_edge AS
    SELECT 'column'::text AS src_kind, c.id       AS src_id,
           'table'::text  AS dst_kind, c.table_id AS dst_id
      FROM catalog_column c
    UNION ALL
    SELECT 'table', c.table_id, 'column', c.id
      FROM catalog_column c
    UNION ALL
    SELECT 'column', h.column_id, 'column_attribute', h.attribute_id
      FROM column_has_attribute h
    UNION ALL
    SELECT 'column_attribute', h.attribute_id, 'column', h.column_id
      FROM column_has_attribute h
    UNION ALL
    SELECT 'column', f.column_id, 'column_attribute', f.attribute_id
      FROM column_semantic_fk f
"""

DROP_JOIN_PATH_EDGE_VIEW_SQL = "DROP VIEW IF EXISTS join_path_edge"

#: The view as something ``select()`` can take, on its **own** ``MetaData``.
#:
#: Not on :data:`METADATA`, deliberately. Alembic autogenerates by diffing that
#: object against the database and cannot tell a view from a table, so a view
#: registered there would be emitted as a ``CREATE TABLE`` on the next
#: autogenerate and then reported as permanent drift. Keeping it in a separate
#: registry means the DDL above stays the single definition of this view, while
#: queries still get column objects instead of raw strings.
VIEWS = MetaData()  # unqualified, for the same reason as METADATA

join_path_edge = Table(
    "join_path_edge",
    VIEWS,
    Column("src_kind", Text, nullable=False),
    Column("src_id", Text, nullable=False),
    Column("dst_kind", Text, nullable=False),
    Column("dst_id", Text, nullable=False),
)

__all__ = [
    "METADATA",
    "column_join",
    "column_union",
    "VIEWS",
    "join_path_edge",
    "JOIN_PATH_EDGE_VIEW_SQL",
    "DROP_JOIN_PATH_EDGE_VIEW_SQL",
    "analysis",
    "catalog_column",
    "catalog_database",
    "catalog_schema",
    "catalog_table",
    "column_attribute",
    "column_has_attribute",
    "column_semantic_fk",
    "column_attribute_term",
    "column_foreign_key",
    "custom_analysis",
    "custom_analysis_sql",
    "pql_analysis",
    "sql_attribute",
    "sql_attribute_sql",
    "sql_attribute_term",
    "sql_query",
    "sql_query_table",
    "sql_query_column",
    "semantic_compilation_history",
    "table_join",
    "table_term",
    "term",
    "text_attribute",
    "zone",
    "zone_target",
]
