"""add description_certified to catalog_table and catalog_column

The UI's certification checkbox PATCHes these through `patch_catalog_node`,
which silently drops properties that have no column -- so without this the
request still returns 200, the checkbox still ticks, and the flag reads back
false forever. Nothing in the ingest writes them, which is why they were easy
to miss when reading the graph: they exist only once a human has certified a
description.

NOT NULL DEFAULT false because every Cypher read was
`coalesce(x.description_certified, false)` -- absent has always meant false.

Revision ID: 325e4825d9ee
Revises: 9ceb971cfdcb
Create Date: 2026-08-12 09:13:57.579886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325e4825d9ee'
down_revision: Union[str, Sequence[str], None] = '9ceb971cfdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_column', sa.Column('description_certified', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='gsf')
    op.add_column('catalog_table', sa.Column('description_certified', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='gsf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_table', 'description_certified', schema='gsf')
    op.drop_column('catalog_column', 'description_certified', schema='gsf')
    # ### end Alembic commands ###
