# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Create the gsf schema

The single baseline migration. GSF is not released and nothing is deployed with
an earlier revision applied, so the history is squashed rather than accumulated:
there is no upgrade path to preserve, and one file that matches
``gsf/dal/schema.py`` is easier to review than a chain that has to be replayed
mentally to know the current shape.

A database built by an earlier chain is structurally identical and can be
adopted with ``alembic stamp --purge head`` -- plain ``stamp`` fails, because
alembic cannot resolve a stored revision that no longer exists.

Two things here are **not** autogenerated and must survive any future squash:
the ``CREATE SCHEMA``, and the ``join_path_edge`` view. Alembic diffs tables,
not views, so it will never emit the second -- and ``find_join_path`` silently
stops finding anything without it.


Revision ID: 46fb8b1368af
Revises:
Create Date: 2026-08-12 16:00:13.330267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from gsf.dal.schema import (
    DROP_JOIN_PATH_EDGE_VIEW_SQL,
    JOIN_PATH_EDGE_VIEW_SQL,
    SCHEMA,
)

# revision identifiers, used by Alembic.
revision: str = "46fb8b1368af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # env.py also creates this, because alembic_version lives in `gsf` and must
    # exist before the first migration can record itself. Repeated here so the
    # migration stands alone for anyone applying it by hand.
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis")),
        schema="gsf",
    )
    op.create_table(
        "catalog_database",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("connection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dialect", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("pulled", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_database")),
        sa.UniqueConstraint("name", name=op.f("uq_catalog_database_name")),
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_database_imported_id",
        "catalog_database",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "column_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("datatype", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.Text(), server_default=sa.text("'semantic'"), nullable=False
        ),
        sa.Column("source_column", sa.Text(), nullable=False),
        sa.Column("term_name", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column(
            "certified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description_suggestion", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_attribute")),
        sa.UniqueConstraint(
            "name",
            "source_column",
            "term_name",
            "table_id",
            "source",
            name="uq_column_attribute_merge_key",
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_column_attribute_imported_id",
        "column_attribute",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_column_attribute_table_id",
        "column_attribute",
        ["table_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_column_attribute_term_name",
        "column_attribute",
        ["term_name"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "custom_analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_analysis")),
        sa.UniqueConstraint("name", name=op.f("uq_custom_analysis_name")),
        schema="gsf",
    )
    op.create_index(
        "ix_custom_analysis_imported_id",
        "custom_analysis",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "pql_analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pql", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pql_analysis")),
        schema="gsf",
    )
    op.create_table(
        "sql_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column(
            "certified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description_suggestion", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "source IS NULL OR source IN ('manual', 'sql', 'table', 'bridgeTable')",
            name=op.f("ck_sql_attribute_source_value"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_attribute")),
        sa.UniqueConstraint("name", name=op.f("uq_sql_attribute_name")),
        schema="gsf",
    )
    op.create_index(
        "ix_sql_attribute_imported_id",
        "sql_attribute",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "sql_query",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("sql_full_query", sa.Text(), nullable=False),
        sa.Column(
            "query_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_counter", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_query_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nodes_count", sa.Integer(), nullable=True),
        sa.Column(
            "join_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "union_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_query")),
        schema="gsf",
    )
    op.create_index(
        "uq_sql_query_text_md5",
        "sql_query",
        [sa.literal_column("md5(sql_full_query)")],
        unique=True,
        schema="gsf",
    )
    op.create_table(
        "term",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.Text(), server_default=sa.text("'semantic'"), nullable=False
        ),
        sa.Column("synonyms", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "name_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term")),
        sa.UniqueConstraint("name", "source", name="uq_term_name_source"),
        schema="gsf",
    )
    op.create_index(
        "ix_term_imported_id", "term", ["imported_id"], unique=False, schema="gsf"
    )
    op.create_index("ix_term_name", "term", ["name"], unique=False, schema="gsf")
    op.create_table(
        "text_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_text_attribute")),
        schema="gsf",
    )
    op.create_table(
        "zone",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone")),
        schema="gsf",
    )
    op.create_index(
        "ix_zone_name_lower",
        "zone",
        [sa.literal_column("lower(name)")],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "catalog_schema",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("database_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["gsf.catalog_database.id"],
            name=op.f("fk_catalog_schema_database_id_catalog_database"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_schema")),
        sa.UniqueConstraint(
            "database_id", "name", name="uq_catalog_schema_database_name"
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_schema_database_id",
        "catalog_schema",
        ["database_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_schema_imported_id",
        "catalog_schema",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "column_attribute_term",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["gsf.column_attribute.id"],
            name=op.f("fk_column_attribute_term_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["gsf.term.id"],
            name=op.f("fk_column_attribute_term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "term_id", name=op.f("pk_column_attribute_term")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_column_attribute_term_term_id",
        "column_attribute_term",
        ["term_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "custom_analysis_sql",
        sa.Column("analysis_id", sa.Text(), nullable=False),
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["gsf.custom_analysis.id"],
            name=op.f("fk_custom_analysis_sql_analysis_id_custom_analysis"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["gsf.sql_query.id"],
            name=op.f("fk_custom_analysis_sql_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "analysis_id", "sql_query_id", name=op.f("pk_custom_analysis_sql")
        ),
        schema="gsf",
    )
    op.create_table(
        "sql_attribute_sql",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["gsf.sql_attribute.id"],
            name=op.f("fk_sql_attribute_sql_attribute_id_sql_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["gsf.sql_query.id"],
            name=op.f("fk_sql_attribute_sql_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "sql_query_id", name=op.f("pk_sql_attribute_sql")
        ),
        schema="gsf",
    )
    op.create_table(
        "sql_attribute_term",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["gsf.sql_attribute.id"],
            name=op.f("fk_sql_attribute_term_attribute_id_sql_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["gsf.term.id"],
            name=op.f("fk_sql_attribute_term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "term_id", name=op.f("pk_sql_attribute_term")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_sql_attribute_term_term_id",
        "sql_attribute_term",
        ["term_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "catalog_table",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("schema_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("pk", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("table_type", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["gsf.catalog_schema.id"],
            name=op.f("fk_catalog_table_schema_id_catalog_schema"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_table")),
        sa.UniqueConstraint("schema_id", "name", name="uq_catalog_table_schema_name"),
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_table_imported_id",
        "catalog_table",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_table_name", "catalog_table", ["name"], unique=False, schema="gsf"
    )
    op.create_index(
        "ix_catalog_table_schema_id",
        "catalog_table",
        ["schema_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "catalog_column",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("data_type", sa.Text(), nullable=True),
        sa.Column("sample_values", sa.Text(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.Column("ordinal_position", sa.Integer(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_catalog_column_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_column")),
        sa.UniqueConstraint("table_id", "name", name="uq_catalog_column_table_name"),
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_column_imported_id",
        "catalog_column",
        ["imported_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_catalog_column_name", "catalog_column", ["name"], unique=False, schema="gsf"
    )
    op.create_index(
        "ix_catalog_column_table_id",
        "catalog_column",
        ["table_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "sql_query_table",
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["gsf.sql_query.id"],
            name=op.f("fk_sql_query_table_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_sql_query_table_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "sql_query_id", "table_id", name=op.f("pk_sql_query_table")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_sql_query_table_table_id",
        "sql_query_table",
        ["table_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "table_join",
        sa.Column("source_table_id", sa.Text(), nullable=False),
        sa.Column("target_table_id", sa.Text(), nullable=False),
        sa.Column(
            "join_columns", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["source_table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_table_join_source_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_table_join_target_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_table_id", "target_table_id", name=op.f("pk_table_join")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_table_join_target",
        "table_join",
        ["target_table_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "table_term",
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_table_term_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["gsf.term.id"],
            name=op.f("fk_table_term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("table_id", "term_id", name=op.f("pk_table_term")),
        schema="gsf",
    )
    op.create_index(
        "ix_table_term_term_id", "table_term", ["term_id"], unique=False, schema="gsf"
    )
    op.create_table(
        "zone_target",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.Column("database_id", sa.Text(), nullable=True),
        sa.Column("schema_id", sa.Text(), nullable=True),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(database_id, schema_id, table_id) = 1",
            name=op.f("ck_zone_target_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["gsf.catalog_database.id"],
            name=op.f("fk_zone_target_database_id_catalog_database"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["gsf.catalog_schema.id"],
            name=op.f("fk_zone_target_schema_id_catalog_schema"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["gsf.catalog_table.id"],
            name=op.f("fk_zone_target_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["gsf.zone.id"],
            name=op.f("fk_zone_target_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_target")),
        schema="gsf",
    )
    op.create_index(
        "ix_zone_target_database_id",
        "zone_target",
        ["database_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_zone_target_schema_id",
        "zone_target",
        ["schema_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_zone_target_table_id",
        "zone_target",
        ["table_id"],
        unique=False,
        schema="gsf",
    )
    op.create_index(
        "ix_zone_target_zone_id", "zone_target", ["zone_id"], unique=False, schema="gsf"
    )
    op.create_table(
        "column_foreign_key",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_foreign_key_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_foreign_key_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column_foreign_key")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_column_foreign_key_target",
        "column_foreign_key",
        ["target_column_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "column_has_attribute",
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["gsf.column_attribute.id"],
            name=op.f("fk_column_has_attribute_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_has_attribute_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "column_id", "attribute_id", name=op.f("pk_column_has_attribute")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_column_has_attribute_attribute_id",
        "column_has_attribute",
        ["attribute_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "column_join",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column(
            "refs", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_join_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_join_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column_join")
        ),
        schema="gsf",
    )
    op.create_table(
        "column_semantic_fk",
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["gsf.column_attribute.id"],
            name=op.f("fk_column_semantic_fk_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_semantic_fk_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "column_id", "attribute_id", name=op.f("pk_column_semantic_fk")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_column_semantic_fk_attribute_id",
        "column_semantic_fk",
        ["attribute_id"],
        unique=False,
        schema="gsf",
    )
    op.create_table(
        "column_union",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column(
            "refs", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_union_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_column_union_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column_union")
        ),
        schema="gsf",
    )
    op.create_table(
        "sql_query_column",
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["gsf.catalog_column.id"],
            name=op.f("fk_sql_query_column_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["gsf.sql_query.id"],
            name=op.f("fk_sql_query_column_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "sql_query_id", "column_id", name=op.f("pk_sql_query_column")
        ),
        schema="gsf",
    )
    op.create_index(
        "ix_sql_query_column_column_id",
        "sql_query_column",
        ["column_id"],
        unique=False,
        schema="gsf",
    )
    # ### end Alembic commands ###

    # Not autogenerated: Alembic diffs tables, not views. Scoped to
    # find_join_path -- see gsf/dal/schema.py for why SEMANTIC_FK is emitted one
    # way here and read both ways elsewhere.
    op.execute(JOIN_PATH_EDGE_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # Before the tables it selects from.
    op.execute(DROP_JOIN_PATH_EDGE_VIEW_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sql_query_column_column_id", table_name="sql_query_column", schema="gsf"
    )
    op.drop_table("sql_query_column", schema="gsf")
    op.drop_table("column_union", schema="gsf")
    op.drop_index(
        "ix_column_semantic_fk_attribute_id",
        table_name="column_semantic_fk",
        schema="gsf",
    )
    op.drop_table("column_semantic_fk", schema="gsf")
    op.drop_table("column_join", schema="gsf")
    op.drop_index(
        "ix_column_has_attribute_attribute_id",
        table_name="column_has_attribute",
        schema="gsf",
    )
    op.drop_table("column_has_attribute", schema="gsf")
    op.drop_index(
        "ix_column_foreign_key_target", table_name="column_foreign_key", schema="gsf"
    )
    op.drop_table("column_foreign_key", schema="gsf")
    op.drop_index("ix_zone_target_zone_id", table_name="zone_target", schema="gsf")
    op.drop_index("ix_zone_target_table_id", table_name="zone_target", schema="gsf")
    op.drop_index("ix_zone_target_schema_id", table_name="zone_target", schema="gsf")
    op.drop_index("ix_zone_target_database_id", table_name="zone_target", schema="gsf")
    op.drop_table("zone_target", schema="gsf")
    op.drop_index("ix_table_term_term_id", table_name="table_term", schema="gsf")
    op.drop_table("table_term", schema="gsf")
    op.drop_index("ix_table_join_target", table_name="table_join", schema="gsf")
    op.drop_table("table_join", schema="gsf")
    op.drop_index(
        "ix_sql_query_table_table_id", table_name="sql_query_table", schema="gsf"
    )
    op.drop_table("sql_query_table", schema="gsf")
    op.drop_index(
        "ix_catalog_column_table_id", table_name="catalog_column", schema="gsf"
    )
    op.drop_index("ix_catalog_column_name", table_name="catalog_column", schema="gsf")
    op.drop_index(
        "ix_catalog_column_imported_id", table_name="catalog_column", schema="gsf"
    )
    op.drop_table("catalog_column", schema="gsf")
    op.drop_index(
        "ix_catalog_table_schema_id", table_name="catalog_table", schema="gsf"
    )
    op.drop_index("ix_catalog_table_name", table_name="catalog_table", schema="gsf")
    op.drop_index(
        "ix_catalog_table_imported_id", table_name="catalog_table", schema="gsf"
    )
    op.drop_table("catalog_table", schema="gsf")
    op.drop_index(
        "ix_sql_attribute_term_term_id", table_name="sql_attribute_term", schema="gsf"
    )
    op.drop_table("sql_attribute_term", schema="gsf")
    op.drop_table("sql_attribute_sql", schema="gsf")
    op.drop_table("custom_analysis_sql", schema="gsf")
    op.drop_index(
        "ix_column_attribute_term_term_id",
        table_name="column_attribute_term",
        schema="gsf",
    )
    op.drop_table("column_attribute_term", schema="gsf")
    op.drop_index(
        "ix_catalog_schema_imported_id", table_name="catalog_schema", schema="gsf"
    )
    op.drop_index(
        "ix_catalog_schema_database_id", table_name="catalog_schema", schema="gsf"
    )
    op.drop_table("catalog_schema", schema="gsf")
    op.drop_index("ix_zone_name_lower", table_name="zone", schema="gsf")
    op.drop_table("zone", schema="gsf")
    op.drop_table("text_attribute", schema="gsf")
    op.drop_index("ix_term_name", table_name="term", schema="gsf")
    op.drop_index("ix_term_imported_id", table_name="term", schema="gsf")
    op.drop_table("term", schema="gsf")
    op.drop_index("uq_sql_query_text_md5", table_name="sql_query", schema="gsf")
    op.drop_table("sql_query", schema="gsf")
    op.drop_index(
        "ix_sql_attribute_imported_id", table_name="sql_attribute", schema="gsf"
    )
    op.drop_table("sql_attribute", schema="gsf")
    op.drop_table("pql_analysis", schema="gsf")
    op.drop_index(
        "ix_custom_analysis_imported_id", table_name="custom_analysis", schema="gsf"
    )
    op.drop_table("custom_analysis", schema="gsf")
    op.drop_index(
        "ix_column_attribute_term_name", table_name="column_attribute", schema="gsf"
    )
    op.drop_index(
        "ix_column_attribute_table_id", table_name="column_attribute", schema="gsf"
    )
    op.drop_index(
        "ix_column_attribute_imported_id", table_name="column_attribute", schema="gsf"
    )
    op.drop_table("column_attribute", schema="gsf")
    op.drop_index(
        "ix_catalog_database_imported_id", table_name="catalog_database", schema="gsf"
    )
    op.drop_table("catalog_database", schema="gsf")
    op.drop_table("analysis", schema="gsf")
    # ### end Alembic commands ###
