# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Create the gsf schema

The single baseline migration. GSF is not released and nothing is deployed with
an earlier revision applied, so the history is squashed rather than accumulated:
there is no upgrade path to preserve, and one file that matches
``gsf/dal/schema.py`` is easier to review than a chain that has to be replayed
mentally to know the current shape.

**This owns ``public`` only.** The vectors live in the ``vdb`` schema, in the two
``langchain_postgres`` collections ``PostgresVDB`` creates and indexes at
runtime (``init_vectorstore_table``, then ``_create_vector_index``) -- not in
these tables and not in this migration. ``include_object`` in ``alembic/env.py``
is what keeps autogenerate from seeing that schema as drift and proposing to
drop it, which is the single most destructive mistake available here.

**The DDL here is unqualified**, and that is deliberate. GSF's tables live in
``public``, and naming the default schema explicitly makes autogenerate report
permanent drift: metadata says ``referent_schema='public'`` for every foreign
key while reflection reports the default schema as ``None``, so Alembic proposes
dropping and recreating all 33 constraints on every run. Placement is guaranteed
instead by the ``search_path`` that ``alembic/env.py`` pins on the migration
connection, and that ``gsf/dal/session.py`` pins on every pooled connection.

There is no ``CREATE SCHEMA``: ``public`` always exists. There is no
``CREATE EXTENSION vector`` either -- nothing here is a vector column, and
``init_vectorstore_table`` creates the extension when it builds a collection.

What is **not** autogenerated, and must survive any future squash, is the
``join_path_edge`` view: Alembic diffs tables, not views, so it will never emit
it, and ``find_join_path`` silently stops finding anything without it.

**A database created before the edge tables were renamed cannot be adopted.**
It still has ``table_term`` where this revision creates ``table__term``, and
because the revision id did not change, alembic considers it current and will
never correct it -- every query then fails on a missing relation. There is no
upgrade path by design: this is one squashed baseline, so recreate the database
(``alembic downgrade base && alembic upgrade head``, or drop and re-run) rather
than trying to stamp it.

That only affects databases built from this branch before the rename. A
database built by an *earlier chain* whose shape already matches can still be
adopted with ``alembic stamp --purge head`` -- plain ``stamp`` fails, because
alembic cannot resolve a stored revision that no longer exists.

Revision ID: 57abbbf6ff90
Revises:
Create Date: 2026-08-30 21:47:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Inlined, not imported from `gsf.dal.schema`.
#
# Importing the constant would make this revision create whatever the
# application currently defines rather than what it defined here, so any later
# edit to the view -- a renamed table, a new branch of the UNION -- would
# silently rewrite what this revision does. A migration is a record of what
# ran; it should not be able to change afterwards.
JOIN_PATH_EDGE_VIEW_SQL = """
CREATE OR REPLACE VIEW join_path_edge AS
    SELECT 'column'::text AS src_kind, c.id       AS src_id,
           'table'::text  AS dst_kind, c.table_id AS dst_id
      FROM catalog_column c
    UNION ALL
    SELECT 'table', c.table_id, 'column', c.id
      FROM catalog_column c
    UNION ALL
    SELECT 'column', h.column_id, 'column_attribute', h.attribute_id
      FROM column__has_attribute h
    UNION ALL
    SELECT 'column_attribute', h.attribute_id, 'column', h.column_id
      FROM column__has_attribute h
    UNION ALL
    SELECT 'column', f.column_id, 'column_attribute', f.attribute_id
      FROM column__semantic_fk f
"""

DROP_JOIN_PATH_EDGE_VIEW_SQL = "DROP VIEW IF EXISTS join_path_edge"

# revision identifiers, used by Alembic.
revision: str = "57abbbf6ff90"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis")),
    )
    op.create_table(
        "catalog_database",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("connection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dialect", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("pulled", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_database")),
        sa.UniqueConstraint("name", name=op.f("uq_catalog_database_name")),
    )
    op.create_index(
        "ix_catalog_database_imported_id",
        "catalog_database",
        ["imported_id"],
        unique=False,
    )
    op.create_table(
        "column_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("datatype", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.Text(), server_default=sa.text("'semantic'"), nullable=False
        ),
        sa.Column("source_column", sa.Text(), nullable=False),
        sa.Column("term_name", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column(
            "certified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description_suggestion", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_attribute")),
        sa.UniqueConstraint(
            "name",
            "source_column",
            "term_name",
            "table_id",
            "source",
            name="uq_column_attribute_merge_key",
        ),
    )
    op.create_index(
        "ix_column_attribute_imported_id",
        "column_attribute",
        ["imported_id"],
        unique=False,
    )
    op.create_index(
        "ix_column_attribute_table_id", "column_attribute", ["table_id"], unique=False
    )
    op.create_index(
        "ix_column_attribute_term_name",
        "column_attribute",
        ["term_name"],
        unique=False,
    )
    op.create_table(
        "custom_analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_analysis")),
        sa.UniqueConstraint("name", name=op.f("uq_custom_analysis_name")),
    )
    op.create_index(
        "ix_custom_analysis_imported_id",
        "custom_analysis",
        ["imported_id"],
        unique=False,
    )
    op.create_table(
        "pql_analysis",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pql", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pql_analysis")),
    )
    op.create_table(
        "semantic_compilation_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('succeeded', 'failed')",
            name=op.f("ck_semantic_compilation_history_status_value"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_compilation_history")),
    )
    op.create_table(
        "sql_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column(
            "certified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description_suggestion", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "source IS NULL OR source IN ('manual', 'sql', 'table', 'bridgeTable')",
            name=op.f("ck_sql_attribute_source_value"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_attribute")),
        sa.UniqueConstraint("name", name=op.f("uq_sql_attribute_name")),
    )
    op.create_index(
        "ix_sql_attribute_imported_id", "sql_attribute", ["imported_id"], unique=False
    )
    op.create_table(
        "sql_query",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("sql_full_query", sa.Text(), nullable=False),
        sa.Column(
            "query_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_counter", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_query_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nodes_count", sa.Integer(), nullable=True),
        sa.Column(
            "join_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "union_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_query")),
    )
    op.create_index(
        "uq_sql_query_text_md5",
        "sql_query",
        [sa.literal_column("md5(sql_full_query)")],
        unique=True,
    )
    op.create_table(
        "term",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.Text(), server_default=sa.text("'semantic'"), nullable=False
        ),
        sa.Column("synonyms", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "name_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term")),
        sa.UniqueConstraint("name", "source", name="uq_term_name_source"),
    )
    op.create_index("ix_term_imported_id", "term", ["imported_id"], unique=False)
    op.create_index("ix_term_name", "term", ["name"], unique=False)
    op.create_table(
        "text_attribute",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_text_attribute")),
    )
    op.create_table(
        "zone",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone")),
    )
    op.create_index(
        "ix_zone_name_lower", "zone", [sa.literal_column("lower(name)")], unique=False
    )
    op.create_table(
        "catalog_schema",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("database_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["catalog_database.id"],
            name=op.f("fk_catalog_schema_database_id_catalog_database"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_schema")),
        sa.UniqueConstraint(
            "database_id", "name", name="uq_catalog_schema_database_name"
        ),
    )
    op.create_index(
        "ix_catalog_schema_database_id", "catalog_schema", ["database_id"], unique=False
    )
    op.create_index(
        "ix_catalog_schema_imported_id", "catalog_schema", ["imported_id"], unique=False
    )
    op.create_table(
        "column_attribute__term",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["column_attribute.id"],
            name=op.f("fk_column_attribute__term_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
            name=op.f("fk_column_attribute__term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "term_id", name=op.f("pk_column_attribute__term")
        ),
    )
    op.create_index(
        "ix_column_attribute__term_term_id",
        "column_attribute__term",
        ["term_id"],
        unique=False,
    )
    op.create_table(
        "custom_analysis__sql",
        sa.Column("analysis_id", sa.Text(), nullable=False),
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["custom_analysis.id"],
            name=op.f("fk_custom_analysis__sql_analysis_id_custom_analysis"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["sql_query.id"],
            name=op.f("fk_custom_analysis__sql_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "analysis_id", "sql_query_id", name=op.f("pk_custom_analysis__sql")
        ),
    )
    op.create_table(
        "sql_attribute__sql",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["sql_attribute.id"],
            name=op.f("fk_sql_attribute__sql_attribute_id_sql_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["sql_query.id"],
            name=op.f("fk_sql_attribute__sql_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "sql_query_id", name=op.f("pk_sql_attribute__sql")
        ),
    )
    op.create_table(
        "sql_attribute__term",
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["sql_attribute.id"],
            name=op.f("fk_sql_attribute__term_attribute_id_sql_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
            name=op.f("fk_sql_attribute__term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "term_id", name=op.f("pk_sql_attribute__term")
        ),
    )
    op.create_index(
        "ix_sql_attribute__term_term_id",
        "sql_attribute__term",
        ["term_id"],
        unique=False,
    )
    op.create_table(
        "catalog_table",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("schema_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("pk", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("table_type", sa.Text(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["catalog_schema.id"],
            name=op.f("fk_catalog_table_schema_id_catalog_schema"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_table")),
        sa.UniqueConstraint("schema_id", "name", name="uq_catalog_table_schema_name"),
    )
    op.create_index(
        "ix_catalog_table_imported_id", "catalog_table", ["imported_id"], unique=False
    )
    op.create_index("ix_catalog_table_name", "catalog_table", ["name"], unique=False)
    op.create_index(
        "ix_catalog_table_schema_id", "catalog_table", ["schema_id"], unique=False
    )
    op.create_table(
        "catalog_column",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("data_type", sa.Text(), nullable=True),
        sa.Column("sample_values", sa.Text(), nullable=True),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.Column("ordinal_position", sa.Integer(), nullable=True),
        sa.Column("imported_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["catalog_table.id"],
            name=op.f("fk_catalog_column_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_column")),
        sa.UniqueConstraint("table_id", "name", name="uq_catalog_column_table_name"),
    )
    op.create_index(
        "ix_catalog_column_imported_id", "catalog_column", ["imported_id"], unique=False
    )
    op.create_index("ix_catalog_column_name", "catalog_column", ["name"], unique=False)
    op.create_index(
        "ix_catalog_column_table_id", "catalog_column", ["table_id"], unique=False
    )
    op.create_table(
        "sql_query__table",
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["sql_query.id"],
            name=op.f("fk_sql_query__table_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["catalog_table.id"],
            name=op.f("fk_sql_query__table_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "sql_query_id", "table_id", name=op.f("pk_sql_query__table")
        ),
    )
    op.create_index(
        "ix_sql_query__table_table_id", "sql_query__table", ["table_id"], unique=False
    )
    op.create_table(
        "table__join",
        sa.Column("source_table_id", sa.Text(), nullable=False),
        sa.Column("target_table_id", sa.Text(), nullable=False),
        sa.Column(
            "join_columns", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["source_table_id"],
            ["catalog_table.id"],
            name=op.f("fk_table__join_source_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_table_id"],
            ["catalog_table.id"],
            name=op.f("fk_table__join_target_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_table_id", "target_table_id", name=op.f("pk_table__join")
        ),
    )
    op.create_index(
        "ix_table__join_target", "table__join", ["target_table_id"], unique=False
    )
    op.create_table(
        "table__term",
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["catalog_table.id"],
            name=op.f("fk_table__term_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
            name=op.f("fk_table__term_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("table_id", "term_id", name=op.f("pk_table__term")),
    )
    op.create_index("ix_table__term_term_id", "table__term", ["term_id"], unique=False)
    op.create_table(
        "zone_target",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.Column("database_id", sa.Text(), nullable=True),
        sa.Column("schema_id", sa.Text(), nullable=True),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(database_id, schema_id, table_id) = 1",
            name=op.f("ck_zone_target_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["catalog_database.id"],
            name=op.f("fk_zone_target_database_id_catalog_database"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["catalog_schema.id"],
            name=op.f("fk_zone_target_schema_id_catalog_schema"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["catalog_table.id"],
            name=op.f("fk_zone_target_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_zone_target_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_target")),
    )
    op.create_index(
        "ix_zone_target_database_id", "zone_target", ["database_id"], unique=False
    )
    op.create_index(
        "ix_zone_target_schema_id", "zone_target", ["schema_id"], unique=False
    )
    op.create_index(
        "ix_zone_target_table_id", "zone_target", ["table_id"], unique=False
    )
    op.create_index("ix_zone_target_zone_id", "zone_target", ["zone_id"], unique=False)
    op.create_table(
        "column__foreign_key",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__foreign_key_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__foreign_key_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column__foreign_key")
        ),
    )
    op.create_index(
        "ix_column__foreign_key_target",
        "column__foreign_key",
        ["target_column_id"],
        unique=False,
    )
    op.create_table(
        "column__has_attribute",
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["column_attribute.id"],
            name=op.f("fk_column__has_attribute_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__has_attribute_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "column_id", "attribute_id", name=op.f("pk_column__has_attribute")
        ),
    )
    op.create_index(
        "ix_column__has_attribute_attribute_id",
        "column__has_attribute",
        ["attribute_id"],
        unique=False,
    )
    op.create_table(
        "column__join",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column(
            "refs", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__join_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__join_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column__join")
        ),
    )
    op.create_table(
        "column__semantic_fk",
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.Column("attribute_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["column_attribute.id"],
            name=op.f("fk_column__semantic_fk_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__semantic_fk_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "column_id", "attribute_id", name=op.f("pk_column__semantic_fk")
        ),
    )
    op.create_index(
        "ix_column__semantic_fk_attribute_id",
        "column__semantic_fk",
        ["attribute_id"],
        unique=False,
    )
    op.create_table(
        "column__union",
        sa.Column("source_column_id", sa.Text(), nullable=False),
        sa.Column("target_column_id", sa.Text(), nullable=False),
        sa.Column(
            "refs", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__union_source_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["catalog_column.id"],
            name=op.f("fk_column__union_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_column_id", "target_column_id", name=op.f("pk_column__union")
        ),
    )
    op.create_table(
        "sql_query__column",
        sa.Column("sql_query_id", sa.Text(), nullable=False),
        sa.Column("column_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["catalog_column.id"],
            name=op.f("fk_sql_query__column_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_query_id"],
            ["sql_query.id"],
            name=op.f("fk_sql_query__column_sql_query_id_sql_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "sql_query_id", "column_id", name=op.f("pk_sql_query__column")
        ),
    )
    op.create_index(
        "ix_sql_query__column_column_id",
        "sql_query__column",
        ["column_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Not autogenerated -- Alembic diffs tables, not views.
    op.execute(JOIN_PATH_EDGE_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(DROP_JOIN_PATH_EDGE_VIEW_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sql_query__column_column_id", table_name="sql_query__column")
    op.drop_table("sql_query__column")
    op.drop_table("column__union")
    op.drop_index(
        "ix_column__semantic_fk_attribute_id", table_name="column__semantic_fk"
    )
    op.drop_table("column__semantic_fk")
    op.drop_table("column__join")
    op.drop_index(
        "ix_column__has_attribute_attribute_id", table_name="column__has_attribute"
    )
    op.drop_table("column__has_attribute")
    op.drop_index("ix_column__foreign_key_target", table_name="column__foreign_key")
    op.drop_table("column__foreign_key")
    op.drop_index("ix_zone_target_zone_id", table_name="zone_target")
    op.drop_index("ix_zone_target_table_id", table_name="zone_target")
    op.drop_index("ix_zone_target_schema_id", table_name="zone_target")
    op.drop_index("ix_zone_target_database_id", table_name="zone_target")
    op.drop_table("zone_target")
    op.drop_index("ix_table__term_term_id", table_name="table__term")
    op.drop_table("table__term")
    op.drop_index("ix_table__join_target", table_name="table__join")
    op.drop_table("table__join")
    op.drop_index("ix_sql_query__table_table_id", table_name="sql_query__table")
    op.drop_table("sql_query__table")
    op.drop_index("ix_catalog_column_table_id", table_name="catalog_column")
    op.drop_index("ix_catalog_column_name", table_name="catalog_column")
    op.drop_index("ix_catalog_column_imported_id", table_name="catalog_column")
    op.drop_table("catalog_column")
    op.drop_index("ix_catalog_table_schema_id", table_name="catalog_table")
    op.drop_index("ix_catalog_table_name", table_name="catalog_table")
    op.drop_index("ix_catalog_table_imported_id", table_name="catalog_table")
    op.drop_table("catalog_table")
    op.drop_index("ix_sql_attribute__term_term_id", table_name="sql_attribute__term")
    op.drop_table("sql_attribute__term")
    op.drop_table("sql_attribute__sql")
    op.drop_table("custom_analysis__sql")
    op.drop_index(
        "ix_column_attribute__term_term_id", table_name="column_attribute__term"
    )
    op.drop_table("column_attribute__term")
    op.drop_index("ix_catalog_schema_imported_id", table_name="catalog_schema")
    op.drop_index("ix_catalog_schema_database_id", table_name="catalog_schema")
    op.drop_table("catalog_schema")
    op.drop_index("ix_zone_name_lower", table_name="zone")
    op.drop_table("zone")
    op.drop_table("text_attribute")
    op.drop_index("ix_term_name", table_name="term")
    op.drop_index("ix_term_imported_id", table_name="term")
    op.drop_table("term")
    op.drop_index("uq_sql_query_text_md5", table_name="sql_query")
    op.drop_table("sql_query")
    op.drop_index("ix_sql_attribute_imported_id", table_name="sql_attribute")
    op.drop_table("sql_attribute")
    op.drop_table("semantic_compilation_history")
    op.drop_table("pql_analysis")
    op.drop_index("ix_custom_analysis_imported_id", table_name="custom_analysis")
    op.drop_table("custom_analysis")
    op.drop_index("ix_column_attribute_term_name", table_name="column_attribute")
    op.drop_index("ix_column_attribute_table_id", table_name="column_attribute")
    op.drop_index("ix_column_attribute_imported_id", table_name="column_attribute")
    op.drop_table("column_attribute")
    op.drop_index("ix_catalog_database_imported_id", table_name="catalog_database")
    op.drop_table("catalog_database")
    op.drop_table("analysis")
    # ### end Alembic commands ###
