# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

"""add pii processed and sample retention to catalog columns

Revision ID: 6347ede6dac1
Revises: c778a7d94c20
Create Date: 2026-10-01 15:12:56.936774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6347ede6dac1"
down_revision: Union[str, Sequence[str], None] = "c778a7d94c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_column",
        sa.Column(
            "pii_processed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "catalog_column",
        sa.Column(
            "sample_values_updated_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_catalog_column_sample_values_updated_at"),
        "catalog_column",
        ["sample_values_updated_at"],
        unique=False,
    )
    # Existing samples predate PII classification. Fail closed: discard them
    # rather than retaining values whose sensitivity has not been established.
    op.execute(sa.text("UPDATE catalog_column SET sample_values = NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_catalog_column_sample_values_updated_at"), table_name="catalog_column"
    )
    op.drop_column("catalog_column", "sample_values_updated_at")
    op.drop_column("catalog_column", "pii_processed")
    # ### end Alembic commands ###
