"""add column-level join and union edges

Revision ID: 63f6c85ccfce
Revises: 325e4825d9ee
Create Date: 2026-08-12 10:40:31.124715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f6c85ccfce'
down_revision: Union[str, Sequence[str], None] = '325e4825d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_join',
    sa.Column('source_column_id', sa.Text(), nullable=False),
    sa.Column('target_column_id', sa.Text(), nullable=False),
    sa.Column('refs', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['source_column_id'], ['gsf.catalog_column.id'], name=op.f('fk_column_join_source_column_id_catalog_column'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_column_id'], ['gsf.catalog_column.id'], name=op.f('fk_column_join_target_column_id_catalog_column'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_column_id', 'target_column_id', name=op.f('pk_column_join')),
    schema='gsf'
    )
    op.create_table('column_union',
    sa.Column('source_column_id', sa.Text(), nullable=False),
    sa.Column('target_column_id', sa.Text(), nullable=False),
    sa.Column('refs', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['source_column_id'], ['gsf.catalog_column.id'], name=op.f('fk_column_union_source_column_id_catalog_column'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_column_id'], ['gsf.catalog_column.id'], name=op.f('fk_column_union_target_column_id_catalog_column'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_column_id', 'target_column_id', name=op.f('pk_column_union')),
    schema='gsf'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_union', schema='gsf')
    op.drop_table('column_join', schema='gsf')
    # ### end Alembic commands ###
