"""Add catalog_column.format

Revision ID: 859d45db5f8a
Revises: affa34ac5a84
Create Date: 2026-08-30 20:34:25.892972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859d45db5f8a'
down_revision: Union[str, Sequence[str], None] = 'affa34ac5a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_column', sa.Column('format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_column', 'format')
    # ### end Alembic commands ###
