"""Add embedding_metadata

Revision ID: affa34ac5a84
Revises: 90329895161c
Create Date: 2026-08-17 21:33:24.939468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'affa34ac5a84'
down_revision: Union[str, Sequence[str], None] = '90329895161c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_column', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('catalog_table', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('column_attribute', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('custom_analysis', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pql_analysis', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sql_attribute', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('term', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('term', 'embedding_metadata')
    op.drop_column('sql_attribute', 'embedding_metadata')
    op.drop_column('pql_analysis', 'embedding_metadata')
    op.drop_column('custom_analysis', 'embedding_metadata')
    op.drop_column('column_attribute', 'embedding_metadata')
    op.drop_column('catalog_table', 'embedding_metadata')
    op.drop_column('catalog_column', 'embedding_metadata')
    # ### end Alembic commands ###
