# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Add descriptions to database and schema

`patch_catalog_node` writes only properties that exist as columns, and these
two tables had none -- so editing a database or schema description returned 200
and silently discarded the text. The graph stored it, so this restores parity.


Revision ID: cd0b2b638f87
Revises: b91c6167562e
Create Date: 2026-08-12 15:54:50.052856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd0b2b638f87"
down_revision: Union[str, Sequence[str], None] = "b91c6167562e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_database",
        sa.Column("description", sa.Text(), nullable=True),
        schema="gsf",
    )
    op.add_column(
        "catalog_database",
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema="gsf",
    )
    op.add_column(
        "catalog_schema",
        sa.Column("description", sa.Text(), nullable=True),
        schema="gsf",
    )
    op.add_column(
        "catalog_schema",
        sa.Column(
            "description_certified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema="gsf",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog_schema", "description_certified", schema="gsf")
    op.drop_column("catalog_schema", "description", schema="gsf")
    op.drop_column("catalog_database", "description_certified", schema="gsf")
    op.drop_column("catalog_database", "description", schema="gsf")
    # ### end Alembic commands ###
