# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Add embedding columns to entity tables

Moves the vector store onto the entities themselves. Each embeddable row gains
its own ``embedding``, the text that produced it, and the database name searches
filter on -- replacing the two side collections in the ``vdb`` schema, where a
vector was linked to its entity only by an id inside a JSON blob and therefore
survived the deletion of the row it described.

``CREATE EXTENSION vector`` moves here for the same reason. It used to happen as
a side effect of ``langchain_postgres``' ``init_vectorstore_table``; once these
columns are the store, nothing else would create it, and a fresh database would
fail on the first ``add_column`` with `type "vector" does not exist`.

Revision ID: ff032ef08929
Revises: a7db0e25b5ea
Create Date: 2026-08-17 20:46:47.879122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders `pgvector.sqlalchemy.vector.VECTOR(...)` but does not
# emit this import; without it the migration fails at import time, not at run
# time, so `alembic upgrade` dies before doing anything.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "ff032ef08929"
down_revision: Union[str, Sequence[str], None] = "a7db0e25b5ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column(
        "catalog_column",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column(
        "catalog_column", sa.Column("embedding_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "catalog_column", sa.Column("embedding_database_name", sa.Text(), nullable=True)
    )
    op.add_column(
        "catalog_table",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column(
        "catalog_table", sa.Column("embedding_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "catalog_table", sa.Column("embedding_database_name", sa.Text(), nullable=True)
    )
    op.add_column(
        "column_attribute",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column(
        "column_attribute", sa.Column("embedding_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "column_attribute",
        sa.Column("embedding_database_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "custom_analysis",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column(
        "custom_analysis", sa.Column("embedding_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "custom_analysis",
        sa.Column("embedding_database_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "pql_analysis",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column("pql_analysis", sa.Column("embedding_text", sa.Text(), nullable=True))
    op.add_column(
        "pql_analysis", sa.Column("embedding_database_name", sa.Text(), nullable=True)
    )
    op.add_column(
        "sql_attribute",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column(
        "sql_attribute", sa.Column("embedding_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "sql_attribute", sa.Column("embedding_database_name", sa.Text(), nullable=True)
    )
    op.add_column(
        "term",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
    )
    op.add_column("term", sa.Column("embedding_text", sa.Text(), nullable=True))
    op.add_column(
        "term", sa.Column("embedding_database_name", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term", "embedding_database_name")
    op.drop_column("term", "embedding_text")
    op.drop_column("term", "embedding")
    op.drop_column("sql_attribute", "embedding_database_name")
    op.drop_column("sql_attribute", "embedding_text")
    op.drop_column("sql_attribute", "embedding")
    op.drop_column("pql_analysis", "embedding_database_name")
    op.drop_column("pql_analysis", "embedding_text")
    op.drop_column("pql_analysis", "embedding")
    op.drop_column("custom_analysis", "embedding_database_name")
    op.drop_column("custom_analysis", "embedding_text")
    op.drop_column("custom_analysis", "embedding")
    op.drop_column("column_attribute", "embedding_database_name")
    op.drop_column("column_attribute", "embedding_text")
    op.drop_column("column_attribute", "embedding")
    op.drop_column("catalog_table", "embedding_database_name")
    op.drop_column("catalog_table", "embedding_text")
    op.drop_column("catalog_table", "embedding")
    op.drop_column("catalog_column", "embedding_database_name")
    op.drop_column("catalog_column", "embedding_text")
    op.drop_column("catalog_column", "embedding")
    # ### end Alembic commands ###
