-- SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
-- All rights reserved.
-- SPDX-License-Identifier: Apache-2.0
--
-- GSF-authored second schema for the Pagila fixture. Not part of upstream
-- Pagila -- see dev_tools/sql/README.md.
--
-- Upstream Pagila is single-schema (everything in `public`), which leaves the
-- catalog's Schema tier untested: a Database -> Schema -> Table hierarchy whose
-- middle level only ever has one member cannot catch a query that silently
-- drops or mis-joins it. Two cases in particular need a second schema:
--
--   * `find_join_path` excludes Schema nodes (labelFilter '-Schema'), so two
--     columns in *different* schemas of the same database must return no path.
--     With one schema that assertion is vacuous.
--   * Zone scoping can target a Schema (ZONE_OF -> Database|Schema|Table).
--     Granting a zone one schema and not the other is the only way to prove
--     schema-level scoping actually filters.
--
-- Deliberately small: the point is a second schema that has real foreign keys
-- back into `public`, not more data.

CREATE SCHEMA IF NOT EXISTS analytics;

-- Cross-schema FK: analytics.rental_summary -> public.film.
-- Exercises a join path that has to traverse a schema boundary.
CREATE TABLE analytics.film_performance (
    film_performance_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id             integer NOT NULL REFERENCES public.film (film_id) ON DELETE CASCADE,
    rental_count        integer NOT NULL DEFAULT 0,
    revenue             numeric(10,2) NOT NULL DEFAULT 0.00,
    last_rented_at      timestamp with time zone,
    CONSTRAINT film_performance_film_id_key UNIQUE (film_id)
);

COMMENT ON TABLE analytics.film_performance IS
    'Per-film rental rollup. Cross-schema FK into public.film.';
COMMENT ON COLUMN analytics.film_performance.revenue IS
    'Total payment amount attributed to this film.';

-- Self-referencing FK inside a non-public schema. Pagila has none anywhere
-- (Chinook covers the same-schema case via Employee.ReportsTo), so this is the
-- only cross-schema recursive shape in the fixture set.
CREATE TABLE analytics.category_rollup (
    category_rollup_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id        integer NOT NULL REFERENCES public.category (category_id) ON DELETE CASCADE,
    parent_rollup_id   integer REFERENCES analytics.category_rollup (category_rollup_id),
    label              text NOT NULL,
    total_rentals      integer NOT NULL DEFAULT 0
);

COMMENT ON TABLE analytics.category_rollup IS
    'Hierarchical category rollup; parent_rollup_id is self-referencing.';

CREATE INDEX film_performance_film_id_idx ON analytics.film_performance (film_id);
CREATE INDEX category_rollup_parent_idx ON analytics.category_rollup (parent_rollup_id);

-- A view in a non-public schema that reads across the boundary, so view
-- handling is not only ever tested inside `public`.
CREATE VIEW analytics.top_films AS
    SELECT f.film_id,
           f.title,
           p.rental_count,
           p.revenue
      FROM analytics.film_performance p
      JOIN public.film f ON f.film_id = p.film_id
     WHERE p.rental_count > 0;

INSERT INTO analytics.film_performance (film_id, rental_count, revenue, last_rented_at)
SELECT f.film_id,
       count(r.rental_id),
       coalesce(sum(pay.amount), 0.00),
       max(r.rental_date)
  FROM public.film f
  LEFT JOIN public.inventory i ON i.film_id = f.film_id
  LEFT JOIN public.rental r    ON r.inventory_id = i.inventory_id
  LEFT JOIN public.payment pay ON pay.rental_id = r.rental_id
 GROUP BY f.film_id;

INSERT INTO analytics.category_rollup (category_id, parent_rollup_id, label, total_rentals)
SELECT c.category_id, NULL, c.name, 0
  FROM public.category c;

-- Give the self-reference some non-null values so recursive traversal has
-- something to walk.
UPDATE analytics.category_rollup child
   SET parent_rollup_id = parent.category_rollup_id
  FROM analytics.category_rollup parent
 WHERE parent.label = 'Family'
   AND child.label IN ('Animation', 'Children')
   AND child.category_rollup_id <> parent.category_rollup_id;
